- cmd/detector/main.go
Builder expects PACK_DETECT_INFO_PATH (detect.toml) to always exist, and
and empty file is ok.
> Detector will always write PACK_DETECT_INFO_PATH

- analyzer.go
- analyzer_test.go
- cmd/analyzer/main.go
- cmd/builder/main.go
- cmd/detector/main.go
- cmd/exporter/main.go
- detector.go
- detector_test.go
- exporter.go
- exporter_test.go
- map.go
- map_test.go
- utils.go
Previously
```
repository = "packs/v3"
buildpacks = ["sh.packs.samples.buildpack.nodejs@0.0.1"]
```
Now
```
repository = "packs/v3"
[[buildpacks]]
id = "sh.packs.samples.buildpack.nodejs"
version = "0.0.1"
```
Signed-off-by: Anthony Emengo <aemengo@pivotal.io>
Signed-off-by: Dave Goddard <dave@goddard.id.au>
> Refactor order.toml to have buildpacks as struct

- detector.go
- detector_test.go
- map.go
- map_test.go
This means we no longer infer :build and :run tags from the repository base
See: https://github.com/buildpack/pack/issues/17
> Split Repository into build and run images

- analyzer.go
- analyzer_test.go
- cmd/exporter/main.go
- env_test.go
- exporter.go
- exporter_test.go
- knative_test.go
- launcher_test.go
Setting UID & GID will set the values on image layer directories and
files.
This allows files to be temporarily stored on file systems where the
user does not have privileges to set uid & gid.
[https://github.com/buildpack/pack/issues/50]
Signed-off-by: Dave Goddard <dave@goddard.id.au>
> Exporter can accept UID & GID

- Dockerfile
PACK_USER_GID is deprecated, leaving here until tooling updates
[https://github.com/buildpack/pack/issues/50]
> Add PACK_GROUP_ID as duplicate of PACK_USER_GID

- exporter.go
- exporter_test.go
- img/actions.go
- metadata.go
* Stores top layer SHA instead of image SHA
* Allows rebasing without access to original run image
> Metadata records run image top layer

- exporter.go
- exporter_test.go
- img/actions.go
- metadata.go
* Changes the run image metadata to record top layer DiffId instead of Digest
* Corrects mistake in https://github.com/buildpack/lifecycle/pull/28
Signed-off-by: Jacques Chester <jchester@pivotal.io>
> run image top layer is diff id

- README.md
Link in old readme is the working documement, which in tern links to the formalized spec. We should link to the formalized spec directly.
> Update README.MD to link to the formalized spec

- images/bin/build-dev
Running "images/bin/devbuild" will compile the lifecycle executables
locally and then generate "packs/samples:dev" from "packs/samples" with
the new lifecycle binaries. This enables the abililty to quickly modify
the lifecycle binaries and then test them out.
> Add script for quick development

- builder.go
- builder_test.go
- cmd/builder/main.go
- cmd/cmd.go
- cmd/detector/main.go
- cmd/exporter/main.go
- cmd/launcher/main.go
- exporter.go
- exporter_test.go
- launcher.go
- launcher_test.go
- metadata.go
This allows for a custom named AppDir, or an AppDir that does not reside under the LaunchDir. The default remains `workspace/app`, but this also cleans up some hard coded references to `"app"`.
I've also introduced a `PACK_APP_DIR` env var to support the launcher, which does not take flags. I'm not sure if this should be a flag. If not, we should maybe add this env var to the spec.
The primary use case is backwards compatibility with pre-v3 platforms, and the potential of a compatibility layer with older buildpacks (i.e. a "shim").
* Should the cmd.DefaultAppDir change if the LaunchDir is set to a custom value?
> Add support for custom app directory with cmd arg

- cmd/exporter/main.go
- exporter.go
- exporter_test.go
* this means that launcher will work if exporter is called with a custom --app flag
> exporter sets PACK_APP_DIR

- launcher.go
- launcher_test.go
* fixes bug in env setting logic
* succeed when metadata has buildpacks that did not contibute layers
> launcher succeeds when buildpack dir does not exist

- map.go
- map_test.go
* fail when order.toml or group.toml references a missing buildpack
[buildpack/lifecycle#49]
> Fail when buildpack is missing

- cmd/exporter/main.go
- exporter.go
- exporter_test.go
- image/factory.go
- image/image.go
- image/local.go
- image/local_test.go
- image/remote.go
- image/remote_test.go
- metadata.go
- testdata/exporter/launcher
- testhelpers/test_image.go
- testmock/image.go
* export launcher as a layer
* set the entrypoint to /lifecycle/launcher
* ensure no cmd
> export launcher

- analyzer.go
- exporter.go
- exporter_test.go
- layers.go
This changes all logging to use a `:` instead of a `/` to separate buildpack ID from layer name. This important because `/` is a valid buildpack ID character.
It also prevents the logging of escaped buildpack IDs, which won't mean anything to a user, who should only ever see the real buildpack ID.
Both of these prevent the implementation detail that buildpacks and layers are directories from bleeding through.
> Improve logging of buildpack ID and layer names

- analyzer.go
- detector.go
- exporter.go
- exporter_test.go
- layers.go
- utils.go
This fixed a problem where the escaped buildpack ID used in a map did not match the ID in the image metadata, which caused the analyzer to invalidate the cache. 
We moved the escape/unescape logic intil `util.go`. The new util funcs are invoked in detector and analyzer. We also fixed a spot where the escaped buildpack ID was used as a key in a map (the real ID should always be used unless it's dealing with the filesystem). Finally, we fixed a spot where analyzer was not unescaping the buildpack dir into an ID.
I think we can avoid problems like this in the future by encapsulating all Buildpack logic related to the filesystem and metadata into a standard `type Buildpack struct` that can be used throughout the codebase. Currently there are numerous buildpack structs, each with their own …
> extract buildpack id/path escaping into utils

- images/samples/Dockerfile
* rename label to io.buildpacks.builder.metadata
* new run-image schema
[buildpack/roadmap#38]
> Update samples metadata

- cmd/analyzer/main.go
- cmd/cmd.go
- cmd/exporter/main.go
- image/auth/env_keychain.go
- image/auth/env_keychain_test.go
- image/auth/legacy_env_keychain.go
- image/auth/legacy_env_keychain_test.go
- image/auth/reference.go
- image/factory.go
- image/local.go
- image/local_test.go
- image/remote.go
- image/remote_test.go
* CNB_REGISTRY_AUTH provides a json map of registry to auth header
* PACK_REGISTRY_AUTH provides a single auth header (deprecated)
[buildpack/roadmap#42]
> Allow multiple image Authentication Headers to be passed to lifecycle

- image/local.go
- restorer.go
- restorer_test.go
The lifecycle unit tests on ci.buildpacks.io run as root. These changes are needed so that they pass. We also test that layers dir user and group are correctly set in this case.
> When tests run as root, test that restorer chown layers dir

- cacher.go
- cacher_test.go
Fixes bug in cacher, cacher should read from the cache label when deciding whether to reuse layers
> Cacher label fix

- cmd/analyzer/main.go
- cmd/cacher/main.go
- cmd/exporter/main.go
- cmd/restorer/main.go
- image/local.go
- image/local_test.go
- image/remote_test.go
- restorer_test.go
- testhelpers/testhelpers.go
- Lifecycle farms out responsibility of pulling to pack
- We want to ensure that pack does not return an error in the
situation where we can pull from remote but the image only exists
locally
[buildpack/pack#90]
> Lifecycle only gets remote or local image, without concern for pulling

- .travis.yml
* release candidate images are now built by concourse (https://ci.buildpacks.io)
* pack travis build will be able to test against these dev images
> travis pushes pack/*:rc images

- cmd/cacher/main.go
- image/image.go
- image/local.go
- image/local_test.go
- image/remote.go
- image/remote_test.go
- testhelpers/test_image.go
- testmock/image.go
- Make image/local and image/remote structs public and
return them from the image factory instead of the
image interface
- Delete the original cache image after the cache step
> Add Delete to local image

- layers.go
`os.Chown` follows the symlink then tries to `chown` the target file. This returns `os.PathError` on broken symlinks (symlinks pointing at a file that doesn't exist).
> Chown symlinks not their targets

- cmd/analyzer/main.go
- cmd/builder/main.go
- cmd/cacher/main.go
- cmd/cmd.go
- cmd/detector/main.go
- cmd/exporter/main.go
- cmd/restorer/main.go
* temporarily set output destination for standard logger to discard before writing a remote image
* surpresses ggcr output
[buildpack/roadmap#45]
> removes "wall of shas"

- image/local.go
- image/local_test.go
* enables pushing local images to registries that enforce shema 1 compat
* enables remote rebasing of images that were originally built locally
[buildpack/lifecycle#104]
> Adds correct number of history entries when saving local image

- detector.go
> Fix detect to log 'Trying group X of Y...' [buildpack/lifecycle#105]

- cmd/analyzer/main.go
- cmd/exporter/main.go
- cred_helpers.go
- cred_helpers_test.go
- testdata/cred_helpers/config1.json
- testdata/cred_helpers/config2.json
* Helpers will only be added if they do not already exist in the docker config
* The credHelpers section is re-used from the docker config rather than re-written
[buildpack/lifecycle#71]
> SetupCredHelpers will not overwrite cred helpers from docker config

- exporter_test.go
- image/fakes/image.go
- Copy all layers on save to a temp dir to mimic the
actual behavior of an image
- Add cleanup method to clean up the temp dir
> Fake image tracks saved layers in a temp dir

- map.go
- map_test.go
This facilitates the implementation of https://github.com/buildpack/pack/issues/113
> Use version from toml file as BuildpackMap key

- cmd/exporter/main.go
- image/image.go
- image/image_test.go
Remove the required `--image` command line argument and default
to `stack.toml` configuration.
When the argument is passed it overrides the `stack.toml` value
Fixes #119
> Exporter defaults to `stack.toml` run image

- cmd/analyzer/main.go
- cmd/builder/main.go
- cmd/cacher/main.go
- cmd/exporter/main.go
- cmd/restorer/main.go
* improves output when lifecycle errors
> Use error message/code helpers correctly

- detector.go
- detector_test.go
Currently, when outputting from group detection, the name of the buildpack is displayed ahead of the condition. For example:
```
Buildpack-1: pass
Buildpack-with-longer-name: pass
BP-short: fail
```
As the example shows, conditions are not vertically aligned. This makes it harder to visually scan for 'pass', 'fail' etc. It also makes it harder to write scripts that automatically parse lifecycle output.
This commit puts the conditions ahead of the buildpack name:
```
pass: Buildpack-1
pass: Buildpack-with-longer-name
fail: BP-short
```
(This PR replaces the pig's breakfast that I and git-duet created in #133)
> Show group detection conditions first

- layers.go
* replaces incorrect TrimRight with TrimSuffix when deriving layer naames from metadata files during export
> Fixes buildpack/pack#198

- .travis.yml
- Makefile
- acceptance/acceptance_test.go
- builder.go
- builder_test.go
- cmd/analyzer/main.go
- cmd/builder/main.go
- cmd/cacher/main.go
- cmd/cmd.go
- cmd/detector/main.go
- cmd/exporter/main.go
- cmd/restorer/main.go
- Added acceptance test suite
Resolves #143 
> Add -version flag to all binaries

- cmd/builder/main.go
- cmd/launcher/main.go
- exporter.go
- exporter_test.go
- go.sum
- metadata/metadata.go
- testhelpers/testhelpers.go
> Add BOM to build metadata label

- cache/image_cache.go
- cmd/cacher/main.go
- cmd/restorer/main.go
- go.mod
- go.sum
- vendor/github.com/buildpack/imgutil/remote/remote.go
- vendor/modules.txt
Switch cacher and restorer to use imgutil remote instead of local.
Make deleting the old cache image optional in image_cache commit.
This change depends on https://github.com/buildpack/imgutil/pull/10.
> Update image cache to save images in a remote repository.

- env.go
- env_test.go
Fixes confusing `.append` syntax that actually prepends.
Also implements a way to provide a delimiter.
Spec PR: https://github.com/buildpack/spec/pull/51
> Implement more complete env var file handling

- builder.go
- cmd/launcher/main.go
- launcher.go
- launcher_test.go
Allow buildpacks to provide `args` that trigger bash-free mode for a given process type.
App developers can use `CMD` with more than one argument to trigger bash-free mode for custom start commands..
Skips profile.d and .profile in bash-free mode.
Spec PR: https://github.com/buildpack/spec/pull/50
> Add support for scratch containers

- cmd/detector/main.go
- compat/compat.go
- compat/compat_test.go
- compat/testdata/buildpacks/buildpack.dup/buildpack.dup.v1/buildpack.toml
- compat/testdata/buildpacks/buildpack.dup/buildpack.dup.v2/buildpack.toml
- compat/testdata/buildpacks/buildpack.single/buildpack.single.v1/buildpack.toml
- compat/testdata/v1.order.dup.toml
- compat/testdata/v1.order.nonexistent.toml
- compat/testdata/v1.order.single.toml
- compat/testdata/v1.order.toml
- compat/testdata/v2.order.toml
Added `compat` package that's pretty self-contained and can be easily removed when we no longer want this functionality.
> Make compatible with pack 0.3.0

- Makefile
- README.md
Based on conversations with @sclevine, it makes sense to have a consistent nested directory structure in order to make validating and detecting lifecycle binaries/descriptors programmatically.
The new structure is now always the following regardless of version:
```
lifecycle.toml
lifecycle/
lifecycle/launcher
lifecycle/detector
lifecycle/exporter
lifecycle/builder
lifecycle/cacher
lifecycle/analyzer
lifecycle/restorer
```
> Make lifecycle package's nested directory consistent

- detector.go
- detector_test.go
- go.mod
Previously the output of the detect phase was way too verbose printing the id and version of every buildpack and whether it passed or failed.  Given large buildpack groups this was a large block of text that was difficult to visually parse for useful information.
A recent change to the output then simplified it to describe only the number of buildpacks that were participating in the build phase, but removed their id and version.  This version of the output ended up being too terse, removing the genuinely useful information of what buildpacks were manipulating your application.
This change splits the difference between the two previous attempts.  It prints the number of buildpacks participating out of the number of options (implying that the others failed or skipped) and then prints the id …
> Concise Output

- analyzer.go
- cmd/cmd.go
- cmd/detector/main.go
- cmd/exporter/main.go
- detector.go
- detector_test.go
- exporter.go
- exporter_test.go
- utils.go
- utils_test.go
Supersedes #173
Here's an example of the info level logging:
```
$ pack build myimage --builder heroku/buildpacks:18 --no-pull
===> DETECTING
[detector] heroku/java 0.14
===> RESTORING
[restorer] Restoring cached layer 'heroku/java:jdk'
[restorer] Restoring cached layer 'heroku/java:maven_m2'
===> ANALYZING
[analyzer] Using cached layer 'heroku/java:jdk'
[analyzer] Using cached layer 'heroku/java:maven_m2'
[analyzer] Writing metadata for uncached layer 'heroku/java:jre'
===> BUILDING
[builder]
...
[builder]
===> EXPORTING
[exporter] Adding layer 'app'
[exporter] Reusing layer 'config'
[exporter] Adding layer 'launcher'
[exporter] Reusing layer 'heroku/java:jre'
[exporter] *** Images:
[exporter]       index.docker.io/library/myimage:latest (a94409e2e599)
===> CACHING
[cacher] Reusing layer …
```
> Make logs more user friendly

- metadata/stack.go
- rebaser.go
- rebaser_test.go
Ensure rebase does not take place if the new base image is based on a different stack
> Rebase fails if new base image has a different stack

- go.mod
- go.sum
- vendor/github.com/buildpack/imgutil/.travis.yml
- vendor/github.com/buildpack/imgutil/Makefile
- vendor/github.com/buildpack/imgutil/README.md
- vendor/github.com/buildpack/imgutil/fakes/image.go
- vendor/github.com/buildpack/imgutil/go.mod
- vendor/github.com/buildpack/imgutil/go.sum
- vendor/github.com/buildpack/imgutil/remote/remote.go
- vendor/modules.txt
- This allow rebases to work on images on artifactory. Artifactory fails rebase as as it run into problems with the history on the img config.
Signed-off-by: Ashwin Venkatesh <avenkatesh@pivotal.io>
This issue is similar to the one described here: GoogleContainerTools/jib#534
> Use version of imgutil that zeros history on remote save

- .travis.yml
- Makefile
Use a go 1.13 feature to build all lifecycle binaries with a single command.
Leads a simpler makefile and also usually faster builds.
> Build all binaries at once

- exporter_test.go
- save.go
```
[builder]
===> EXPORTING
[exporter] Adding layer 'app'
[exporter] Reusing layer 'config'
[exporter] Adding layer 'launcher'
[exporter] Reusing layer 'heroku/java:jre'
[exporter] *** Images:
[exporter]       index.docker.io/library/myimage:latest (ae41bec06d78)
[exporter]
[exporter] *** Image ID: ae41bec06d78175a2bfadbf0d39dd0e5ba9dcf046a5d8c2d76b8205eb419eac1
===> CACHING
[cacher] Reusing layer 'heroku/java:jdk'
[cacher] Caching layer 'heroku/java:maven_m2'
Successfully built image myimage
```
> Log digest or image id as info level instead of debug

- analyzer_test.go
- exporter_test.go
exporter_test.go referred to non-existent 'assertNil'
analyzer_test.go re-implemented a function from testhelpers
> Clean up usage of assertNil in tests

- cmd/exporter/main.go
- exporter.go
- exporter_test.go
* uses correct digest reference for remote images
* uses image ID for daemon images
Fixes #199
> Fix run-image-reference in image metadata

- archive/tar.go
- archive/tar_test.go
Umask can change the permissions of the file being written leading to the created file having different permissions than it should according to the tar archive.
For example, with umask 027, two tests fail:
```
Suite: tar
Total: 9 | Focused: 0 | Pending: 0
x.x......
Passed: 7 | Failed: 2 | Skipped: 0
--- FAIL: TestTar (0.00s)
--- FAIL: TestTar/tar (0.00s)
--- FAIL: TestTar/tar/#ReadTarArchive/extracts_a_tar_file (0.00s)
tar_test.go:77:   os.FileMode(
-       s"-rw-r-----",
+       s"-rw-r--r--",
  )
--- FAIL: TestTar/tar/#ReadTarArchive/doesn't_alter_permissions_of_existing_folders (0.00s)
tar_test.go:92:   os.FileMode(
-       s"drwxr-----",
+       s"drwxr--r--",
  )
FAIL
FAIL    command-line-arguments  0.073s
```
> Fix permissions when untarring files with umask

- archive/tar.go
When the cacher encounters an error writing the tar archive, you get an error like this:
```
Caching layer 'io.greenhouse.some-buildpack:some-layer'
Layer 'io.greenhouse.some-buildpack:some-layer' SHA: sha256:8e4f67fe86cb12dc6233c86b08434ee7db1e03e722e46fa3c80a9041f63cb437
Reusing layer 'io.greenhouse.some-buildpack:other-layer'
Layer 'io.greenhouse.some-buildpack:other-layer' SHA:
ERROR: failed to cache: previous image did not have layer with sha ''
```
With  this change, the error properly bubbles up:
```
Caching layer 'io.greenhouse.some-buildpack:some-layer'
Layer 'io.greenhouse.some-buildpack:some-layer' SHA: sha256:8e4f67fe86cb12dc6233c86b08434ee7db1e03e722e46fa3c80a9041f63cb437
ERROR: failed to cache: caching layer 'io.greenhouse.some-buildpack:other-layer': open …
```
> Fix error checking when writing archives for cached layers

- metadata.go
- rebaser.go
- rebaser_test.go
> Allow Rebaser to parse metadata of older app images

- Makefile
`jq` is used by the test buildpacks. This PR fails out early if `jq` isn't detected on the `$PATH`.
> verify jq is installed before running unit tests

- exporter.go
Fixes #239
This is the quick fix. Some refactoring of the slices logic would allow for more thorough edge case testing and could help prevent issues like this in the future.
> exporter no longer tries to delete app dir

- archive/tar.go
- go.mod
+ Avoid changing file permissions two times
+ Reuse the copy buffer
+ Don’t check if a folder exists if we just created it
On my Mac, with a 1.2G tarball (go-build cache folder), this takes consistently around 4.5s rather than consistently around 6s.
It’s harder to test with a cold fs cache, though.
Signed-off-by: David Gageot <david@gageot.net>
> Faster Untar

- archive/digest.go
- archive/digest_test.go
- archive/tar.go
The computation of the sh256 digest is now done concurrently to the tarball creation.
This gives a 30% boost on my tests (with a hot cache)
Signed-off-by: David Gageot <david@gageot.net>
> Faster sha256 computation

- Makefile
- README.md
- acceptance/acceptance_test.go
- archive/tar.go
- archive/tar_unix.go
- archive/tar_windows.go
We made the minimal source changes to cross-compile on Windows.
Resolves #234
This does not yet make any lifecycle functionality work on Windows but also does not change Linux functionality. This only allows `make build-windows package-windows` to create lifecycle tarballs containing actual `.exe` files.
Additional Issues will iteratively add Windows functionality to lifecycle. See upcoming issues: https://github.com/buildpacks/lifecycle/issues?q=is%3Aissue+is%3Aopen+label%3Aos%2Fwindows
> Add make package targets for windows and darwin

- Makefile
- cmd/flags.go
- cmd/lifecycle/exporter.go
- exporter.go
- exporter_test.go
- project_metadata.go
Implements https://github.com/buildpacks/spec/pull/68
- Adds ProjectMetadataPath flag to Export command
- ~~If flag is not provided,~~ sets default path to "./project-metadata.toml"
- If project metadata path is not present or cannot be unmarshalled, it logs for info and
continues
- Provides types for ProjectMetadata ~~, and Git source code~~
- Amends Export method parameters to include ProjectMetadata
- Tests provided for Export method for context when Project Metadata is
provided
[#170698084]
> Implements RFC0013 for app source project metadata

- cmd/flags.go
- cmd/lifecycle/exporter.go
- exporter.go
- exporter_test.go
- metadata.go
- testdata/exporter/cache-layer-no-contents/layers/config/metadata.toml
- testdata/exporter/escaped-bpid/layers/config/metadata.toml
- testdata/exporter/previous-image-exists/layers/config/metadata.toml
- testdata/exporter/previous-image-not-exist/layers/config/metadata.toml
Implements https://github.com/buildpacks/rfcs/blob/master/text/0017-pack-build-default-process-flag.md (buildpacks/rfcs#28)
`exporter` accepts `-process-type` flag
* defaults to `CNB_PROCESS_TYPE` env var, if set
* no default if `CNB_PROCESS_TYPE` is not set
If provided, it sets `CNB_PROCESS_TYPE` on the exported image.
> Default process type flag

- .github/workflows/build.yml
- .travis.yml
- README.md
Signed-off-by: Simon Jones <simonjones@vmware.com>
This PR adds a Github actions for new PRs and pushes to master which triggers unit testing, building and packaging of the lifecycle artifact for Linux.
I do have an outstanding concern that this defaults to version `0.0.0`, however this is not intended to immediately replace the current build process, so versioned artifacts will continue to be created and uploaded to our GCS bucket with the correct version number.
> Build linux artifact in a Github Action

- .github/workflows/build.yml
- priv/user_linux.go
If user does not own volume, check thoroughly for write permissions before attempting to chown.
context: https://github.com/buildpacks/lifecycle/issues/271#issuecomment-598926266
> support world writable pvcs on k8

- .github/workflows/build.yml
- priv/user_linux.go
Correct `gid` is good enough to satisfy `EnsureOwner` that permissions are correct
Fixes: #271
> play nice with k8s PodSecurityContext fsGroup

- cmd/flags.go
- cmd/lifecycle/exporter.go
* no default for deprecated -image flag
* when decided whether -run-image flag is passed, compare to the default
* Fixes #274
> fixes error setting run-image with CNB_RUN_IMAGE env var

- exporter_test.go
- project_metadata.go
This will prevent missing project metadata from writing a noisy project metadata value: `{\"source\":{\"type\":\"\",\"version\":null,\"metadata\":null}}`
This will instead produce an empty json document `{}`
> Add omitempty to project metadata types

- auth/env_keychain.go
- auth/env_keychain_test.go
- cmd/lifecycle/analyzer.go
- cmd/lifecycle/exporter.go
- cmd/lifecycle/main.go
- cmd/lifecycle/rebaser.go
* Uses DefaultKeychain if CNB_REGISTRY_AUTH is not set
* Uses EnvKeychain if CNB_REGISTRY_AUTH is set
* Doesn't fallback on the default keychain if the EnvKeychain returns anonymous
* This fixes an error caused by the lifecycle attempting to read  in root's home dir after dropping privileges
* Generally platforms use either CNB_REGISTRY_AUTH or a docker config.json, not both
Signed-off-by: Natalie Arellano <narellano@pivotal.io>
> Fixes anonymous auth when analyze/export run as root

- priv/user_linux.go
runtime.LockOSThread() slows down the exporter and is unecessary now that we use the musllibc implementation of setres{g,u}id. It was originally added when we attempted to use the go runtime implementation of SetRes{G,U}ID, which only works on a single thread.
> Don't lock os thread

- cmd/lifecycle/creator.go
- cmd/lifecycle/exporter.go
- cmd/lifecycle/rebaser.go
- image/image.go
- image/image_test.go
* Fixes: #295
Doesn't validate that all destination tags have a matching registry when
exporting to the daemon (this is unnecessary in the daemon case)
> Better error message when an image reference fails to parse

- go.mod
- go.sum
Harbor doesn't seem to return the error code specified in the registry api docs when a manifest is not found. This PR bumps `imgutil` to a version that gracefully handles all 404s without regard for the specific error code
Resolves #303
> Handle 404s from harbor

- acceptance/launcher_test.go
The order of vars printed by env is non-deterministic
> Fixes flaky launcher test

- cache/image_cache.go
- cache/image_cache_test.go
With the reproducibility improvements, it often happens that the old and
new cache images are the same. The original image should not be
deleted in this case.
This is an issue with remote images, where the image is deleted by
digest and both the old and new images share the same digest.
Signed-off-by: Lukas Berger <bergerl@google.com>
> Do not delete cache image when exporting cache if it is the same as before

- builder.go
- builder_test.go
- detector.go
- detector_test.go
- testdata/buildpack/bin/build
- testdata/buildpack/bin/build.bat
- testdata/buildpack/bin/detect
- testdata/buildpack/bin/detect.bat
> Sets CNB_BUILDPACK_DIR in bp execution env during detect and build

- acceptance/launcher_test.go
- acceptance/testdata/launcher/posix/container/layers/config/metadata.toml
- acceptance/testdata/launcher/posix/container/layers/some_buildpack/some_layer/env.launch/worker/WORKER_VAR
- acceptance/testdata/launcher/posix/container/layers/some_buildpack/some_layer/env/WORKER_VAR
- acceptance/testdata/launcher/posix/container/layers/some_buildpack/some_layer/profile.d/worker/0_bp_worker_profile.sh
- acceptance/testdata/launcher/windows/container/layers/config/metadata.toml
- acceptance/testdata/launcher/windows/container/layers/some_buildpack/some_layer/env.launch/worker/WORKER_VAR
- acceptance/testdata/launcher/windows/container/layers/some_buildpack/some_layer/env/WORKER_VAR
- acceptance/testdata/launcher/windows/container/layers/some_buildpack/some_layer/profile.d/worker/0_bp_worker_profile.bat
- launch/launcher.go
- launch/launcher_test.go
Include process type specific paths when processing env vars during launch.
Spec: https://github.com/buildpacks/spec/pull/98
> Implement process type specific env vars

- env/build.go
- env/build_test.go
- env/launch.go
- env/launch_test.go
Signed-off-by: Malini Valliath <mvalliath@pivotal.io>
Signed-off-by: Victoria Henry<vhenry@pivotal.io>
Signed-off-by: Andrew Meyer <meyeran@vmware.com>
> Fix case-sensitivity bug when initializing env vars

- Makefile
- tools/Dockerfile.windows
This a fix for `make docker-run-windows` on top of #340 
It changes the Windows-daemon-only target
> Fix make docker-run-windows branch merge-slice-fix

- cmd/exit.go
- cmd/lifecycle/detector.go
- detector.go
- detector_test.go
Platforms should have the ability to tell the difference between a detector failure because of no passing buildpacks and a detector failure because of no passing buildpacks that _had errors_ during detect.
Detector will now return a `100` or `101` depending on how detection failed.
[Issue #306](https://github.com/buildpacks/lifecycle/issues/306)
[Updatd Spec](https://github.com/buildpacks/spec/blob/platform/0.4/platform.md#outputs)
> feat: use more specific codes during detect

- detector.go
- detector_test.go
Builpacks which do not return pass (`0`) or fail (`100`) will now have their output as well as the resulting `err` message logged at info level.
[Issue](https://github.com/buildpacks/lifecycle/issues/283)
> feat: make buildpack detection errors info level

- Makefile
- archive/compress_test.go
- archive/writer.go
- archive/writer_test.go
- layers/writer.go
- tools/image/main.go
- tools/packager/main.go
* Uses Normalizing tar writer to fix paths when running on windows
* Move lifecycle.toml to top-level in archive
* Zeros UID/GID
> packaging fixes

- lifecycle.toml
We said this likely wasn't necessary in (RFC-0049)[https://github.com/buildpacks/rfcs/blob/main/text/0049-multi-api-lifecycle-descriptor.md#backwards-compatibility]
But... after seeing how `pack` fails when provided the new format (an NPE) I think making `lifecycle.toml` backwards compatible is probably the right call.
> Make lifecycle.toml backwards compatible

- builder.go
- builder_test.go
- cmd/lifecycle/builder.go
- cmd/lifecycle/main.go
- detector.go
> Remove top-level version from BOM

- builder.go
- builder_test.go
Addresses updates to:
#357 
#330 
This change perserves `metadata.version` keys in the buildpack plan provided to `0.2` buildpacks. `0.2` buildpacks may expect `metadata.version` or `version` and therefore we provide both. The same change has been made for the Platform`0.3` BOM. Users of existing APIs may receive extra keys but no keys are removed.
> Leave metadata.version in buildpack plan provided to 0.2 buildpacks

- go.mod
- go.sum
- tools/go.mod
- tools/go.sum
- tools/image/main.go
* bumps to new imgutil that always adds security descriptor record
* allow windows image builds on any OS
> Fix PAX headers in windows lifecycle images

- tools/image/main.go
I manually released the `buildpacksio/lifecycle:0.9.0` and `buildpacksio/lifecycle:latest` images to fix this.
In the future I think we need a way configure the lifecycle image in `pack` and in the `pack` acceptance tests to enable better testing of lifecycle images.
> Sets working dir to /layers in lifecycle image

- exporter.go
- exporter_test.go
- tools/go.sum
Fixes #376 
When platform API >= 0.4 and default process type is not defined,
warn and set the entrypoint to /cnb/lifecycle/launcher
> Warn when exporting with non-existing process type

- go.mod
- go.sum
- tools/go.mod
- tools/go.sum
Fixes #385
This pulls in a fix for duplicate environment variables.
> Bump imgutil

- go.mod
- go.sum
- rebaser.go
- rebaser_test.go
- tools/go.mod
- tools/go.sum
- utils.go
- Update matching labels present on both images to value on run image
- Remove matching labels no long present on run image
- Add matching labels that are newly added on run image
- Ignore non-matching labels on both working and run image
Ref #390
> Sync io.buildpacks.stack.* labels from run image during rebase

- acceptance/testdata/launcher/windows/Dockerfile
- tools/image/main.go
The lifecycle currently uses a Windows base image called `nanoserver`, which is going out of support soon.  This change updates the base image to `servercore:ltsc2019`
> Update windows base image to use LTSC Server Core 2019

- Makefile
- cmd/version.go
This requires extra processing in cmd/version.go because Version when it includes the commit will not contain
'-dirty'.
> Remove double parsing of commit sha in Makefile

- analyzer_test.go
- cache/image_cache_test.go
- cmd/lifecycle/creator.go
- cmd/lifecycle/exporter.go
- cmd/lifecycle/rebaser.go
- cmd/lifecycle/restorer.go
- exporter_test.go
- go.mod
- go.sum
- golangci.yaml
- layers/digest_test.go
- restorer_test.go
- testhelpers/testhelpers.go
- tools/go.mod
- tools/go.sum
- utils.go
Enables `errcheck` linter in golangci-lint. Fixes missing error checks!
> Enable errcheck

- launch/launcher.go
- launch/launcher_unix.go
- launch/launcher_windows.go
- launch/shell.go
- layers.go
- layers/slices.go
- layers/slices_test.go
Fixes 2 issues:
**Issue 1** Unsafe use of `filepath.Glob`
We previous used filepath.Glob for four purposes:
1. Globbing slice files - This was updated to use a combination of filepath.Walk and filepath.Match to match children of the app dir by relative path. We already had logic to unsure that no files outside of the app dir were included. A test was added to confirm this and prevent regressions
2. Globbing profile scripts - This commit changes the implementation so that we no longer use filepath.Glob here
3. Globbing layer.toml files - This commit changes the implementation so that we no longer use filepath.Glob here
4. Test logic - unsafe use of filepath.Glob is unchanged in the test code
**Issue 2** Slice globbing on Windows
According to the buildpack API in the CNB Speciication slice …
> Remove all unsafe usage of filepath.Glob

- Makefile
- tools/Dockerfile
* caches go modules in a volumes
* uses docker build to create linux compilation image
> Faster linux builds

- tools/image/main.go
This is necessary because of this bug in imgutil https://github.com/buildpacks/imgutil/issues/54.
Fixes image build failures https://github.com/buildpacks/lifecycle/actions/runs/304821754
> Use manifest tag instead of manifest list tag as windows base image

- acceptance/testdata/launcher/windows/Dockerfile
- tools/image/main.go
Nanoserver 1809 will now be supported through January 2024. Therefore, we should use this image because it is smaller than ltsc2019.
* https://github.com/microsoft/Windows-Containers/issues/52
> Changes windows base image back to nanoserver:1809

- launch/bash.go
- launch/bash_test.go
Our magic bash command was mising some important curly brances and therefore the tenth argument was being set to the equivalent of "${1}0" instead of "${10}".
Resolves #445
> Bash process handles more than 9 args correctly

- metadata.go
- rebaser.go
- rebaser_test.go
- utils.go
Implemented as discussed [here](https://github.com/buildpacks/lifecycle/issues/425). Using the `io.buildpacks.stack.mixins` label of the working and new run image, lifecycle will now verify that mixins are present on the new base image prior to the rebase operation.
> feature: validate mixins during rebase

- layers/slices.go
- layers/slices_test.go
I took a stab at fixing #455 but I have some questions.
`filepath.Clean` seemed like the easiest fix, but it would also have the effect of making other patterns match - e.g., `some-dir//some-other-dir` would match `some-dir/some-other-dir` and I am not sure this is what we want.
Also it seems important to validate this change against the linked repro (spring-boot-buildpack) but having limited knowledge of Spring Boot, I am not sure how to do that.
> Slices: Clean pattern before matching

- acceptance/analyzer_test.go
- acceptance/testdata/analyzer/analyze-image/Dockerfile
- acceptance/testdata/analyzer/analyze-image/container/some-other-layers/group.toml
- acceptance/testdata/analyzer/cache-dir/committed/io.buildpacks.lifecycle.cache.metadata
- api/apis.go
- cmd/command.go
- cmd/flags.go
- cmd/lifecycle/analyzer.go
- cmd/lifecycle/builder.go
- cmd/lifecycle/creator.go
- cmd/lifecycle/detector.go
- cmd/lifecycle/exporter.go
- cmd/lifecycle/main.go
- cmd/lifecycle/rebaser.go
- cmd/lifecycle/restorer.go
- lifecycle.toml
Notes:
* This commit introduces platfromAPI 0.5 as a supported API.
* The changes apply only for platformAPI >= 0.5.
* The path of the relevant files is being changed as part of Args after parsing the flags.
* Allow the user to set the layers flag in the detector.
Fixes #393
> Change defaults that are depending on the working dir to be under <layers>

- cache/image_cache.go
When using image cache, the commit of new cache deletes the old cache. There is a check for if there is a previous cache image, but that check was happening after the new cache was written to that tag.
https://github.com/buildpacks/lifecycle/issues/453
> fix: Do not delete cache-img if the cache-img did not exist

- README.md
* Resolves #311
Mentions the existence of `creator` in the README and tweaks phase descriptions slightly.
This PR doesn't even attempt to fix most of our README problems but it fixes one large omission.
> Mention creator in README

- cmd/lifecycle/exporter.go
- Was: "ERROR: failed to new app image"
- Now: "ERROR: failed to create new app image"
Signed-off-by: Micah Young <ymicah@vmware.com>
> Fixes export error message

- cmd/lifecycle/exporter.go
- go.mod
- go.sum
- tools/go.mod
- tools/go.sum
Falls back to slower behavior if the daemon does not accept empty layers. This allows the lifecycle to be compatible with podman which requires all layers to be preset during a docker load: buildpacks/imgutil#80
Fixes "manifest.json had unexpected number of entries"  errors in analyze, export, and rebase resulting from a bug in our daemon save logic: buildpacks/imgutil#63
> Bumps imgutil to fix daemon image bugs

- exporter_test.go
- layers.go
- testdata/exporter/build-metadata/bad-layers/buildpack.id/build.toml
Although parsing `build.toml` and `launch.toml` as layer descriptors doesn't cause issues if they are valid (because they are incorrectly assumed to be launch=false layers) if something goes wrong while parsing, this code can produce very misleading errors without this fix in place.
For example, I accidentally added `[[build.bom]]` instead of `[[bom]]` to a `build.toml` and got this misleading error from the exporter:
```
ERROR: failed to export: failed to parse metadata for layers '[samples/java-maven:build samples/java-maven:launch]'
```
> Explicitly ignores build.toml and launch.toml when finding layers

- exporter.go
This will keep the output consistent for users of older platform APIs
> Omit build bom from report.toml if empty

- cmd/lifecycle/exporter.go
Fixes NPE in `exporter` on first build.
> Guards against nil analyzed image

- launch/launcher.go
- launch/launcher_test.go
When processing the environment continue when a buildpack has no layers dir instead of returning.
> Fixes when a buildpack with no layers stops launch env processing

- detector.go
Fixes #510 
@jonfriesen and I had been trying to debug a weird regression we started seeing after we upgraded from a `0.8.x` version of lifecycle to `0.10.1`. Eventually we narrowed it down to random Buildpacks intermittently having their `CNB_BUILDPACK_DIR` env var set to that of a different Buildpack like Jon described in #510.
The issue seems to be stemming from the fact that the goroutine runs `info.Detect(c)` which does the following:
```go
cmd.Env = c.FullEnv
if b.Buildpack.ClearEnv {
cmd.Env = c.ClearEnv
}
cmd.Env = append(cmd.Env, EnvBuildpackDir+"="+b.Dir)
```
Copying the slice `c.FullEnv`/`c.ClearEnv` as-is and then appending to it inside the goroutine is unsafe. `cmd.Env` and `c.FullEnv` share the same underlying array. When it is appended to it affects the underlying array on …
> Fix goroutine race in detector

- .github/workflows/build.yml
This fixes the build as the `ubuntu-latest` tag is now `20.04`.
See [more](https://github.com/actions/virtual-environments/issues/1816)
I expect this to be temporary once we discuss how to make the test that broke less brittle. I wanted to make sure we had an easy path to getting `main` green again.
> Pin GitHub workflows to ubuntu-18.04

- env/env.go
- env/env_test.go
Symlinks to directories should be evaluated so they can be skipped when building env.
Fixes #526
> Follow symlinks when building env from files.

- acceptance/detector_test.go
- acceptance/testdata/detector/Dockerfile
- cmd/flags.go
- cmd/lifecycle/detector.go
This adds an optional path to the resolution of `order.toml`. The new path is `<layers>/order.toml` and will be selected prior to `/cnb/order.toml` if there is a file present. This will allow platforms to create an `order.toml` in the `<layers>` volume in another step and have that accepted automatically by the lifecycle when. that occurs.
Blocked on:
> Add <layers>/order.toml resolution to detector

- cmd/lifecycle/creator.go
The placeholder replacement code was not being executed in `creator` flow
> Fix creator not replacing placeholder path for -order

- analyzer_test.go
- buildpack/v06/encoderdecoder.go
The launch, build and cache flags are set to false.
Make this change to allow the buildpack author to append new values to the flags instead of changing the existing ones
(according to the toml's spec, there shouldn't be duplicate values).
> buildpack API >= 0.6 - omit the types table when encoding the layer.toml file

- buildpack/build_test.go
rename `<layers>/<layer>` to `<layers>/<layer>.ignore` if the `launch`, `build` and `cache` flags aren't specified
> Add a unit test

- .gitpod.yml
- README.md
Hi buildpacks team! 👋
here is a PR that fully-automates the dev setup of buildpacks/lifecycle with Gitpod, providing anyone with a pre-built, browser-based development environment in one click:
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/buildpacks/lifecycle/pull/604)
* Comes with all buildpack lifecycle dependencies pre-installed (Go, Docker...)
* Runs `make  build` ahead-of-time so you don't need to wait
* Gives anyone immediate access to the pre-compiled buildpacks CLI, and allows to easily edit & rebuild the code
I hope this can make life easier for contributors, and for maintainers who need to review many PRs (hint: you can already open this PR in Gitpod to easily review & test it without messing up your local checkout).
I'm …
> Gitpodified the repo

- .github/workflows/build.yml
- acceptance/analyzer_test.go
- go.mod
- go.sum
- tools/go.mod
- tools/go.sum
Bumps imgutil and uses new registry helpers
- Requires GHA firewall exception, which was previously added by docker container
- Port is dynamic so all traffic must be allowed to the host IP, but only traffic that originates from host IP (excludes inbound all public traffic)
Signed-off-by: Micah Young <ymicah@vmware.com>
> Bump imgutil and uses new registry helpers

- acceptance/analyzer_test.go
- cmd/lifecycle/analyzer.go
See [here](https://github.com/buildpacks/spec/pull/225#pullrequestreview-663490720)
We should still be taking in `<image>` to represent the write location and optionally the `<previous-image>` if no explicitly defined. This re-aligns with the spec and `creator` behavior.
> Re-Align analyzer with spec and creator

- .github/workflows/build.yml
- .github/workflows/draft-release.yml
- .github/workflows/post-release.yml
- RELEASE.md
Resolves #561 
Note that publishing a pre-release doesn't re-tag the associated lifecycle image. I was concerned that consumers of the lifecycle might mistake it for a "real" release (see [Paketo issue](https://github.com/paketo-buildpacks/packit/issues/144), this has been fixed, but there could be other consumers with this problem). [pack](https://github.com/buildpacks/pack/blob/e53adb9c9e55b33e830f2e92bc4741cc32dc24f7/.github/workflows/delivery-docker.yml#L6) doesn't appear to ship pack images for pre-releases. 
However it's worth noting that potentially just publishing a pre-release on GitHub could confuse some people - perhaps we should do some socializing of this change.
> Add GHA for shipping release candidates

- acceptance/analyzer_test.go
- acceptance/testdata/analyzer/analyze-image/Dockerfile
- acceptance/testdata/analyzer/analyze-image/Dockerfile.windows
- acceptance/testdata/analyzer/run-image/Dockerfile
- acceptance/testdata/analyzer/run-image/Dockerfile.windows
- cmd/flags.go
- cmd/lifecycle/analyzer.go
- cmd/lifecycle/creator.go
- platform/files.go
- stack_validation.go
- stack_validation_test.go
- tools/go.sum
- utils.go
- utils_test.go
During analyze, Platform 0.7 and above will validate the build and stack image if the data is available to do so.
Addresses Part of: #471
[Spec](https://github.com/buildpacks/spec/blob/platform/0.7/platform.md#analyzer) being implemented:
> The lifecycle MUST fail if the stack ID of the `<run-image>` does not match `<stack-id>`
> Validate stack during analyze phase

- layers/launcher.go
launcher.go currently swallows error messages from `os.Stat`, `tar.FileInfoHeader` and `os.Open`.
We should change this, as the downstream errors can have different reasons, which are interesting to the enduser. E.g. `os.Stat` could return an error when the file is not found or when permissions are wrong.
> Fix: launcher.go swallows downstream error messages

- .github/workflows/build.yml
- .github/workflows/draft-release.yml
- .github/workflows/post-release.yml
- RELEASE.md
As discussed in implementation sync. We'll semver tag the images but NOT update `latest`.
> Semver tag release candidate lifecycle images

- .github/workflows/build.yml
Otherwise the build will fail because secrets are not provided.
We don't intend to push an image, so there is no reason to login.
> Don't try to login to docker for PRs

- Makefile
- priv/user_linux.go
The use of cgo was introduced in https://github.com/buildpacks/lifecycle/pull/268, instead of using golang.org/x/sys/unix. I believe syscall.Setres{g,u}id is the platform-independent equivalent, but I admit I don't know enough about this to be confident this isn't a regression.
If this is acceptable, it could be a step toward unblocking https://github.com/buildpacks/lifecycle/issues/435
@ekcasey
> Use syscall package instead of cgo

- .github/workflows/build.yml
- Makefile
- acceptance/acceptance_test.go
- acceptance/analyzer_test.go
- acceptance/detector_test.go
- acceptance/launcher_test.go
- acceptance/restorer_test.go
- testhelpers/binaries.go
- tools/image/main.go
This PR makes make targets explicit about the GOARCH being used, in addition to the GOOS.
This changes `make build` to build for `linux/amd64`, `windows/amd64`, and newly, `linux/arm64`. Binaries are built to paths like `out/$GOOS-$GOARCH/lifecycle`, etc.
This also changes the CI image build process to build and attach the `amd64` binary to the build, and to include the `linux/arm64` image in the manifest list.
Acceptance tests were updated to build arch-specific binaries and to look for them in the new correct place.
Open questions:
- This PR doesn't currently change the fact that the `linux/amd64` image is pushed and tagged to `buildpacksio/lifecycle:$FOO-linux`, when it maybe should get pushed to `...linux-amd64`. We can push to both to avoid breaking people, if that's preferred.
- …
> Build lifecycle binaries and images for linux/arm64

- .github/workflows/build.yml
@natalieparellano 
The image built after #659 includes two manifests with the `linux/amd64` platform, when one should be `linux/arm64`.
> Fix typo in build.yaml related to arm64 build

- auth/env_keychain.go
- auth/env_keychain_test.go
> Don't print header when failed to parse

- tools/image/main.go
Fixes #675
We need to translate the daemon architecture from x86_64
> Fix `make build-image-linux-amd64`

- acceptance/analyzer_test.go
We're not modifying the image fixtures, so they could be created once per suite instead of once per `it`. This will make test organization easier.
> Refactor analyzer fixtures

- .github/workflows/build.yml
- .github/workflows/draft-release.yml
- .github/workflows/post-release.yml
- tools/packager/main.go
> Generate checksums during package

- .github/workflows/draft-release.yml
This should make it slightly easier to run these workflows in a fork.
Unfortunately it [doesn't look like there's an easy context value for just the repo name](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context), so this might still be difficult for people who have a fork with a different name.
> Use repository owner from GitHub Actions context

- acceptance/analyzer_test.go
- go.mod
- go.sum
- This Pull Request is created after [PR #646](https://github.com/buildpacks/lifecycle/pull/646) was merged
After merging  [PR #646](https://github.com/buildpacks/lifecycle/pull/646) we agreed to refactor the analyzer tests and simplifying the number of docker registries we are using. 
- The PR removes the `authRegistry` and the `readOnlyRegistry` and replaces them with just 1 `testRegistry` that uses the `ImagePrivilges` approach implemented in  imgUtil repo [PR #126](https://github.com/buildpacks/imgutil/pull/126) to configure the registry to handle the required behaviors.
- This PR depends on imgUtil repo [PR #126](https://github.com/buildpacks/imgutil/pull/126)
> WIP - Refactoring analyzer tests to use custom docker registry

- .github/workflows/build.yml
- .github/workflows/post-release.yml
See https://github.com/sigstore/cosign-installer
This downloads pre-built binaries from official sources, which should save some time since we can avoid building the binary ourselves.
@natalieparellano
> Install cosign using official GitHub Action

- .github/workflows/build.yml
> Run tests on arm in CI

- acceptance/analyzer_test.go
- acceptance/exporter_test.go
- analyzer.go
- analyzer_test.go
- cmd/lifecycle/analyzer.go
- cmd/lifecycle/exporter.go
- platform/files.go
> Run image should be locked to a digest in analyzed.toml

- .github/workflows/post-release.yml
- acceptance/analyzer_test.go
- acceptance/exporter_test.go
- acceptance/restorer_test.go
- analyzer.go
- analyzer_test.go
- api/version.go
- api/version_test.go
- builder.go
- buildpack/build.go
- buildpack/detect.go
- buildpack/v05/encoderdecoder.go
- buildpack/v06/encoderdecoder.go
- cmd/flags.go
- cmd/launcher/main.go
- cmd/lifecycle/analyzer.go
- cmd/lifecycle/creator.go
- cmd/lifecycle/exporter.go
- cmd/lifecycle/restorer.go
- env/env.go
- exporter.go
- exporter_test.go
- launch/launcher.go
- launch/process.go
- launch/shell.go
- layers.go
- rebaser.go
- restorer.go
- restorer_test.go
Signed-off-by: Sambhav Kothari <skothari44@bloomberg.net>
> Update github actions to use cosign v1.2.0

- acceptance/testdata/detector/container/cnb/custom_buildpacks/always_detect_buildpack/always_detect_buildpack_version/buildpack.toml
- api/apis.go
We missed this when backing out asset packages.
> Buildpack api 0.7 is not supported

- .github/workflows/post-release.yml
Also there is no need to parse the digest from `crane tag` because it does not change.
This will make the code less brittle.
> Use the correct tag when signing the sbom

- Makefile
- acceptance/launcher_test.go
- acceptance/variables_windows.go
- archive/extract_test.go
- archive/reader.go
- cmd/command.go
- cmd/lifecycle/exporter.go
- cmd/lifecycle/rebaser.go
- cmd/logs.go
- exporter_test.go
- golangci.yaml
- image/image.go
- launch/launch.go
- layer_metadata_restorer_test.go
- layers/factory.go
- layers/slices.go
- rebaser.go
- testhelpers/docker.go
- testhelpers/vars_darwin.go
- testhelpers/vars_linux.go
- tools/image/main.go
As a new contributor to lifecycle, when I cloned the code and ran `make all`, the lint step failed with `golangci-lint` segfaulting (I'm on Mac, fwiw). The version of golangci-lint we're pinned to (1.30.0) [does not support go 1.17](https://github.com/golangci/golangci-lint/issues/2197).
The goal of this PR is to get this step to work out of the box, which will smooth out the new contributor experience, while also bringing our linting up to date.
I've updated golagci-lint to the latest version (1.42.1). This update brought with it warnings about some of the tools it uses underneath being deprecated:
```
WARN [runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive. 
WARN [runner] The linter …
```
> Get `make lint` to work out of the box with Go 1.17

- acceptance/analyzer_test.go
- cmd/lifecycle/analyzer.go
Fixes https://github.com/buildpacks/lifecycle/issues/754
This bug is really pointing to an ever-more-urgent need to refactor aspects of the `cmd` package, but I am holding off on that for now.
> Don't print warnings about run image for older platform apis

- builder_test.go
- buildpack/bom.go
- buildpack/bomfile.go
- buildpack/build_test.go
Updates to SBOM based on [spec discussion](https://github.com/buildpacks/spec/pull/269).
> Use sbom instead of bom as filename prefix for consistency

- api/apis.go
- lifecycle.toml
- tools/packager/main.go
If we forget to update lifecycle.toml, this could cause some platform validations to fail.
To verify:
Manually edit api/apis.go to contain some new apis:
```
var (
Platform  = newApisMustParse([]string{"0.3", "0.4", "0.5", "0.6", "0.7", "0.99"}, nil)
Buildpack = newApisMustParse([]string{"0.2", "0.3", "0.4", "0.5", "0.6", "0.99"}, nil)
)
```
Run `make clean build-linux-amd64 package-linux-amd64 && cd out && tar xzvf lifecycle-*+linux.x86-64.tgz && cat lifecycle.toml`
Before:
lifecycle.toml is not updated
After:
lifecycle.toml is updated
> Automatically update lifecycle.toml when new apis are added

- buildpack/bom.go
- buildpack/bomfile.go
- buildpack/build.go
- buildpack/build_test.go
if you are on buildpack API version 0.7 and output old style bom information, return error 🛑 
if you are on buildpack API version <0.7 and output new style SBoM information, show warning ⚠️ 
cc: @dmikusa-pivotal
> Error when previous bom is specified on buildpack API 0.7

- buildpack/descriptor.go
- buildpack/store_test.go
- buildpack/testdata/by-id/A/v1.clear/buildpack.toml
- buildpack/testdata/by-id/A/v1/buildpack.toml
This change was suggested in the spec PR review.
> Update buildpack.toml to use sbom-formats

- .github/workflows/build.yml
We are currently seeing failures such as [here](https://github.com/buildpacks/lifecycle/actions/runs/1517187264) because pack upgraded to go 1.17 in the latest release and the runner only comes with 1.15 by default.
> Fix pack acceptance

- go.mod
- go.sum
The lifecycle and imgutil will be on the same version of ggcr.
> Bumps imgutil and also updates indirect dependencies

- cmd/command.go
- cmd/lifecycle/analyzer.go
- cmd/lifecycle/builder.go
- cmd/lifecycle/creator.go
- cmd/lifecycle/detector.go
- cmd/lifecycle/exporter.go
- cmd/lifecycle/main.go
- cmd/lifecycle/rebaser.go
- cmd/lifecycle/restorer.go
cmd/lifecycle/analyzer.go is hard to make changes to, for a few reasons:
* there are several nested structs: `analyzeCmd`, `analyzeArgs`, and `platform06` and it's not obvious where to add new fields
* a lot of branching logic in `analyzeCmd.Args()`
This PR tries to address these problems by:
* Removing the `platform06` struct and moving its fields to the other structs, but with the prefix `legacy`
* ~Making clear where fields belong by renaming `analyzeArgs` -> `analyzeInputsForCreator`~
* Cleaning up a few fields that creator was providing without needing to
* Moving some logic from `analyzeCmd.Args()` into helper functions
If we like this pattern I could make similar changes for other phases if needed.
> Organize analyze inputs

- restorer_test.go
The only place the restorer uses the buildpack api is [here](https://github.com/buildpacks/lifecycle/blob/42be2d161b283c8f831f78a695df4c7c35782709/restorer.go#L48). It's probably not necessary to run the test suite for every combination of buildpack api & platform api (36 combinations) when there are only two modes of buildpack behavior.
To take it further, looking at the comment [here](https://github.com/buildpacks/lifecycle/blob/42be2d161b283c8f831f78a695df4c7c35782709/restorer.go#L56-L59), the edge case mentioned "the cache was cleared between builds and the analyzer that wrote the files is on a previous version of the lifecycle" is quite narrow and unlikely to occur given that the last lifecycle with the old behavior is several months old. I wonder if we could just have the restorer …
> Don't run restorer tests for every buildpack api

- buildpack/bom.go
- buildpack/bomfile.go
- buildpack/build.go
- buildpack/build_test.go
as opposed to throwing an error. This allows for non-breaking platform migration from legacy bom table to sbom format
This commit partially reverts 880a801db2d4bfbb39671a66f7aadd96c0231e37
> Warn when legacy bom is specified on buildpack API 0.7

- restorer.go
- restorer_test.go
...that were restored from the previous image.
Found this bug while verifying #794
> If there are is no sbom layer in the cache, still copy sbom files for launch

- extender/kaniko/dockerfile_applier.go
CustomPlatform doesn't work quite like the other Kaniko options. 
Internally it must always have a value, normally achieved by this bit of code.. 
https://github.com/GoogleContainerTools/kaniko/blob/3589382378b89f6868623efdeb33da338195526e/cmd/warmer/cmd/root.go#L91-L97
The extender seems to bypass that code, leading to that option not having a value at runtime, which leads to failures if any Dockerfile parsed by the extender tries to pull a new image (eg, if it tries to use FROM to reference a new image). 
```
time="2022-02-17T18:34:55Z" level=info msg="Retrieving image manifest redhat/ubi8-minimal:latest"
time="2022-02-17T18:34:55Z" level=info msg="Retrieving image redhat/ubi8-minimal:latest from registry index.docker.io"
time="2022-02-17T18:34:55Z" level=error msg="Error parsing the …
```
> Add default value for CustomPlatform

- buildpack/build.go
- buildpack/build_test.go
- buildpack/detect.go
- buildpack/detect_test.go
- buildpack/testdata/buildpack/bin/build
- buildpack/testdata/buildpack/bin/build.bat
- buildpack/testdata/buildpack/bin/detect
- buildpack/testdata/buildpack/bin/detect.bat
As described in RFC 100, set the following environment variables when
running buildpack executables, which correspond to their positional
arguments.
In `detect`:
- CNB_PLATFORM_DIR
- CNB_BUILD_PLAN_PATH
In `build`:
- CNB_LAYERS_DIR
- CNB_PLATFORM_DIR
- CNB_BP_PLAN_PATH
Fixes #806.
Fixes #807.
Signed-off-by: Mikey Boldt <mboldt@vmware.com>
> Set env vars for positional args in build and detect

- acceptance/analyzer_test.go
- acceptance/exporter_test.go
- api/apis.go
- cmd/lifecycle/exporter.go
- go.mod
- go.sum
- platform/platform_test.go
Platforms can set `SOURCE_DATE_EPOCH` to control the timestamp on the exported app images.
See https://github.com/buildpacks/lifecycle/issues/809 for more details.
> Support SOURCE_DATE_EPOCH

- internal/layer/sbom_restorer.go
- internal/layer/sbom_restorer_test.go
> When restoring sbom files, silently ignore if the bp layers directory does not exist

- acceptance/creator_test.go
- analyzer.go
- builder.go
- builder_test.go
- buildpack/bom.go
- buildpack/bomfile.go
- buildpack/build.go
- buildpack/build_test.go
- cache.go
- cmd/lifecycle/builder.go
- exporter.go
- exporter_test.go
- internal/encoding/utils.go
- internal/encoding/utils_test.go
- internal/layer/sbom_restorer.go
- platform/files.go
- platform/files_test.go
- restorer.go
- restorer_test.go
- utils.go
Resolves https://github.com/buildpacks/lifecycle/issues/808
> Write sbom.legacy.json files for newer platform api

- .github/workflows/build.yml
- .github/workflows/post-release.yml
- Makefile
- acceptance/testdata/launcher/Dockerfile
- acceptance/testdata/launcher/Dockerfile.windows
- acceptance/testdata/launcher/exec.d/go.mod
- go.mod
- launch/exec_d_windows.go
Now that go 1.18 is out, go 1.16 is no longer supported.
Fixes https://github.com/buildpacks/lifecycle/issues/838
> Upgrade to go 1.17

- .gitignore
- acceptance/exporter_test.go
- acceptance/testdata/exporter/Dockerfile
- acceptance/testdata/exporter/container/other_layers/analyzed.toml.placeholder
- cache/image_cache.go
- exporter_test.go
- go.mod
- go.sum
The following fix initialized the cached image to add an empty layer in the case is needed 
Fixes #830
Signed-off-by: Juan Bustamante <jbustamante@vmware.com>
> Add empty layer before saving on remote images

- cmd/launcher/cli/launcher.go
- cmd/launcher/main.go
This exposes the launcher's entrypoint to be public. This would allow other projects to easily wrap the launcher to inject their own custom logic. The only public interface it exposes is that there should be a RunLauncher function that takes nil arguments and returns an error.
This would greatly help simplify the logic we have for the custom launcher to deal with https://github.com/buildpacks/rfcs/issues/210
> Make runLaunch public

- cmd/lifecycle/creator.go
On newer platform API versions, the lifecycle is not printing an expected ANALYZING step header.
> Fix: Output ANALYZING phase heading

- acceptance/analyzer_test.go
- acceptance/detector_test.go
- analyzer_test.go
With #635 and #634 we added unit tests that cover some of the things we're currently testing in acceptance.
> Refactor: remove redundant acceptance tests

- detector.go
- detector_test.go
This was an oversight in #860. A buildpack and extension with the same ID when part of the same group should both be able to detect.
> Fix: a buildpack and extension with the same ID can both detect

- .gitignore
- api/apis.go
- buildpack/build.go
- buildpack/build_test.go
- buildpack/files.go
- Buildpacks using the newer buildpack API must use the new launch.toml format
- The older format is still allowed on older buildpack API versions
Issue: https://github.com/buildpacks/lifecycle/issues/870
> Allow new buildpack API to use new launch.toml format 

- buildpack/generate.go
- cmd/lifecycle/detector.go
- cmd/lifecycle/exporter.go
- generator.go
Fixes for..
- detecting build.Dockerfiles (generate.go readOutputFilesExt) {missing logic to look for build.Dockerfileand add to br.Dockerfiles with appropriate DockerfileKind}
- detecting run.Dockerfiles during scanning for updated runImage (generator.go checkNewRunImage) {missing use of launch.Escape for extID}
- filtering the buildplan based on capabilities extensions provides (generator.go now returns filteredBuildPlan as part of GenerateResult, and detector.go uses that plan when supplied to update plan.toml as part of Exec)
> fixes from testing.

- .github/workflows/build.yml
(but before they are re-tagged with a non-dev version)
This will alert us if it becomes necessary to publish a new patch outside of the normal release cadence.
Resolves #824
> Scan dev lifecycle images after they are published 

- .github/workflows/check-latest-release.yml
Together with release/0.14.2, resolves https://github.com/buildpacks/lifecycle/issues/905.
Lifted from https://github.com/buildpacks/libcnb/blob/main/.github/workflows/pb-update-go.yml.
> Add GitHub Actions workflow to update go when a new version is available

- .github/workflows/build.yml
- builder_test.go
- buildpack/build_test.go
- buildpack/files.go
- cmd/launcher/cli/launcher.go
- exporter.go
- exporter_test.go
- launch/decode_test.go
- launch/launch.go
- launch/launcher.go
- launch/launcher_test.go
- launch/process.go
- launch/process_test.go
- launch/shell.go
- platform/files.go
- testhelpers/testhelpers.go
This is a first step to implementing #322. This PR is updating our internal structs to allow for a slice of commands while keeping the external API and behavior the same. A future PR will implement handling multiple commands depending on the API version and changing the behavior of the launcher and metadat file output changes.
> Allow storing multiple commands instead of a single string

- buildpack/dockerfile.go
- generator.go
Validation by simple dockerfile parser.. 
Validation added as additional step after generation before dockerfiles are copied. Build fails if validation fails.
Currently instruction validation is MUST, to weaken to SHOULD, modify VerifyBuildDockerfile/VerifyRunDockerfile appropriately to just print the err from the verify(Build|Run)Verbs invocation, rather than returning it. 
All dockerfile logic moved to dockerfile.go, uses small visitor to inspect each instruction (skipping comments, and directives, and multiline continues).. assumes 1st arg for instruction is on same line with instruction, will most likely be true for the only args we care about (ARG and FROM). 
Original checkNewRunImage dockerfile logic patched to use new parser to be tolerant of comments / empty lines in dockerfile
> Dockerfile validation

- .grype.yaml
> Add .grype.yaml to ignore known non-impactful CVEs

- acceptance/creator_test.go
- acceptance/testdata/creator/container/cnb/buildpacks/samples_hello-world/0.0.1/bin/build
- cmd/lifecycle/creator.go
- cmd/lifecycle/restorer.go
- internal/selective/write_test.go
- testhelpers/docker.go
When platform API is at least 0.10, run the restore phase always but pass
-skip-restore as skip layers to skip layer metadata and SBOM restoration
This ensures:
- In the 5 phase invocation, the restorer can always run (for extension purposes)
- The 5 phase invocation will match the creator invocation
> Fix creator restore bug

- acceptance/analyzer_test.go
- acceptance/builder_test.go
- acceptance/detector_test.go
- acceptance/extender_test.go
- acceptance/restorer_test.go
- cmd/lifecycle/extender.go
- cmd/lifecycle/restorer.go
- extender.go
- extender_test.go
- handlers.go
- internal/extend/kaniko/dockerfile_applier.go
- internal/extend/kaniko/dockerfile_applier_darwin.go
- internal/extend/kaniko/dockerfile_applier_linux.go
- internal/extend/kaniko/dockerfile_applier_windows.go
- internal/selective/write_test.go
- platform/extend_inputs.go
- platform/files.go
- testhelpers/testhelpers.go
- testmock/config_handler.go
Favors passing the reference via analyzed.toml
To reflect this commit in the platform spec PR: https://github.com/buildpacks/spec/pull/320/commits/f0a3ef244ab34f467f3530117f2aec6cf18b7bf1
> Remove <image> as an argument to the extender

- acceptance/builder_test.go
- builder_test.go
- buildpack/build_test.go
- buildpack/files.go
- exporter_test.go
- launch/decode_test.go
- launch/launch.go
- launch/launch_test.go
- launch/launcher.go
- launch/launcher_test.go
- launch/process.go
- launch/process_test.go
- launch/shell.go
- platform/files.go
Moved the dynamic process serialization to a new field type and off of process. The TOML that was previously generated was not expected and the TOML library we use doesn't seem to have a way to render the table the way we expect. Making a new type for the single field `command` allows us to render the TOML the way we want.
Fixes: buildpacks/lifecycle#945
> Fix regression in metadata.toml rendering

- launch/launch.go
This should fix the Windows tests (pack acceptance)
> Use json to marshal command entry for older platform

- launch/launch.go
- launch/launch_test.go
- platform/files.go
Following up on https://github.com/buildpacks/lifecycle/pull/946 and https://github.com/buildpacks/lifecycle/pull/947, this handles special characters and adds an `UnmarshalJSON` method to `Command` for library consumers.
> Fix special character escaping when marshaling launch process

- go.mod
- go.sum
Replaces https://github.com/buildpacks/lifecycle/pull/948 without bumping kaniko
> Bump golang.org/x/sys from 0.1.0 to 0.2.0

- Makefile
- acceptance/creator_test.go
- acceptance/exporter_test.go
- acceptance/phase_test.go
- api/apis.go
- buildpack/bomfile.go
- cache.go
- exporter.go
- exporter_test.go
- internal/path/defaults.go
- internal/path/defaults_unix.go
- internal/path/defaults_windows.go
- layers/launcher.go
- layers/launcher_test.go
- lifecycle.toml
- tools/packager/main.go
> Generate lifecycle sbom

- acceptance/extender_test.go
- acceptance/testdata/extender/Dockerfile
- acceptance/testdata/extender/container/cnb/buildpacks/samples_hello-extensions/0.0.1/bin/build
- cmd/lifecycle/extender.go
> Fix: set HOME for provided user after build image extension (#960)

- .github/workflows/build.yml
We need to configure git to use line feeds on Windows, otherwise
the test fixtures and hence the layer diff IDs will be different from the test expectations.
> Fix pack acceptance with 0.28.0-rc1

- acceptance/exporter_test.go
- buildpack/bomfile.go
- cmd/lifecycle/cli/flags.go
- cmd/lifecycle/creator.go
- cmd/lifecycle/exporter.go
- exporter.go
- exporter_test.go
- internal/path/defaults.go
- internal/path/defaults_unix.go
- internal/path/defaults_windows.go
- lifecycle_unix_test.go
- lifecycle_windows_test.go
- platform/create_inputs.go
- platform/defaults.go
- platform/defaults_unix.go
- platform/defaults_windows.go
- platform/export_inputs.go
- platform/launch/defaults.go
- platform/launch/defaults_unix.go
- platform/launch/defaults_windows.go
- platform/lifecycle_inputs.go
- tools/packager/main.go
As a follow on to https://github.com/buildpacks/lifecycle/pull/944, this PR introduces a `-launcher-sbom` flag to the exporter & creator so that users who supply their own launcher can supply an SBOM for that launcher.
Related spec PR: https://github.com/buildpacks/spec/pull/332/files?diff=split&w=1
> Add launcher SBOM input

- cmd/lifecycle/rebaser.go
- go.mod
- go.sum
- rebaser.go
- rebaser_test.go
- save.go
- testhelpers/testhelpers.go
This allows a rebase by a image digest reference.
Resolves [#983](https://github.com/buildpacks/lifecycle/issues/983)
Here is an example command & output:
```
➜ lifecycle rebase -previous-image localhost:5003/cnb/rebase/demo@sha256:916a9e100569ee521b86d03b8499b9b93d7d256d6e838868ae720295f2ea2f76 localhost:5003/cnb/rebase/demo:v1 localhost:5003/cnb/rebase/demo:rebased
Saving localhost:5003/cnb/rebase/demo:v1...
*** Images (sha256:07c07bba660126053df38987bbb6098784b9348226ac689ded17f588c6708ed5):
localhost:5003/cnb/rebase/demo:v1
localhost:5003/cnb/rebase/demo:rebased
```
> allow passing previous image in rebase cmd

- acceptance/creator_test.go
- acceptance/testdata/creator/container/cnb/buildpacks/samples_hello-world/0.0.1/bin/build
- cache/caching_image.go
On shared hardware it's not guaranteed for the second build to take less than 3 seconds 
We can at least test that the second build is faster than the first
> Fix creator acceptance test flake

- analyzer.go
Before: "Previous image with name <run image name> not found" 
After: "Image with name <run image name> not found"
> Fix log message when run image not found

- Makefile
- unit and acceptances tests are tee'd to a file in /out (which is already .gitignore-d)
- this makes it easier to grep for failures after the test run, if you're into that kind of thing
- rhymes with a previous change in pack: https://github.com/buildpacks/pack/pull/1585
> Preserves test output for easier grepping

- go.mod
- go.sum
Fixes non-impactful CVE: https://github.com/buildpacks/lifecycle/actions/runs/4205731394/jobs/7298681140#step:28:27
Fixes #1018
> Bump containerd

- buildpack/layermetadata_test.go
Layer Metadata is straightforward, adding a test to act as a living document.
> Add Layer Metadata test as living doc

- archive/extract.go
- archive/extract_test.go
The pax global header headers is currently not handled, but it should not cause a failure with the side effect of not uncompressing an otherwise valid tarball.
> Ignore pax global header in tar extract

- .github/workflows/check-latest-release.yml
Use the new way of producing outputs in a github action as the old way is deprecated and will be removed (31st May 2023).
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Replace deprecated GHA ::set-output syntax

- .github/workflows/build.yml
- go.mod
- go.sum
- tools/image/main.go
Further context in Slack: https://cloud-native.slack.com/archives/C0331B5QS02/p1679426001027039
Now that `gcr.io/distroless/static` has OCI media types, our lifecycle image, which is built from that image, has OCI media types. This causes `docker manifest create` on older versions of `docker` to fail with `manifest unknown: OCI manifest found, but accept header does not support OCI manifests `. 
We could create our own tooling to make the manifest list with OCI media types, avoiding the need to use `docker`, but `docker manifest inspect` may fail if the resulting index has OCI media types. This will be [fixed](https://github.com/moby/moby/issues/43126) in newer versions of docker but may cause problems for users who haven't yet upgraded.
Given that it's a fairly annoying failure with no …
> Fix buildpacksio/lifecycle manifest create

- .github/workflows/draft-release.yml
- .github/workflows/post-release.yml
While "release candidate" is still a pre-release, it conveys more readiness than a "pre-release" or "preview release".
We'd like to ship pre-release lifecycle artifacts
so that users can test out new features without them being fully implemented as they would in a release candidate.
> Enable pre-releases in addition to release candidates

- platform/files.go
- platform/files_test.go
in a previous commit, like shakespearean teenagers in love, we got our stars crossed.
> os and arch: buildpack targets should have stars

- platform/files.go
- rebaser.go
- rebaser_test.go
- [Validate OS, Arch, Variant and optional labels on rebase](https://github.com/buildpacks/lifecycle/commit/bb8522457d9c59adb83a4b817cfad2b272bdbc51)
- [Copy io.buildpacks.base.* labels on rebase](https://github.com/buildpacks/lifecycle/commit/68655c8219ca980e74175a8a237739e51d5c5228)
For https://github.com/buildpacks/lifecycle/issues/744
> 0.12 Rebase Validation and Label Sync

- acceptance/analyzer_test.go
- acceptance/creator_test.go
- cmd/lifecycle/analyzer.go
- cmd/lifecycle/rebaser.go
- platform/files.go
- platform/files_test.go
- platform/lifecycle_inputs.go
- platform/resolve_analyze_inputs_test.go
- platform/resolve_create_inputs_test.go
- platform/resolve_inputs.go
- platform/testhelpers/image_strategy.go
Instead of simply picking the first run-image, the lifecycle will select the first **accessible** reference, if there's no match by registry.
See https://github.com/buildpacks/spec/pull/357
> Verify read access while selecting best `run-image` mirror

- cmd/lifecycle/cli/command.go
- cmd/lifecycle/main.go
In working through https://github.com/buildpacks/lifecycle/issues/1007 it was hard to know if the lifecycle had even started when we were stuck in a loop trying to get the auth, because the first log lines emitted by the lifecycle were emitted after the Analyzer had started.
If we had this logging in place beforehand,
we would have known the problem was somewhere in Privileges()
> Add more logging so we know when the lifecycle actually starts

- extender.go
- extender_test.go
should resolve two bullet points on https://github.com/buildpacks/lifecycle/issues/1057
> extender: better uid checks and error if it stay as root

- platform/files.go
- rebaser.go
- rebaser_test.go
if the provided run image does not match existing metadata.
See https://github.com/buildpacks/spec/pull/360
> When rebasing, update stack/runImage key in lifecycle metadata label

- analyzer.go
- cmd/lifecycle/exporter.go
- cmd/lifecycle/rebaser.go
- exporter.go
- exporter_test.go
- platform/labels.go
- rebaser.go
- rebaser_test.go
see: https://github.com/buildpacks/lifecycle/issues/1057
> metadata label is more clearly named and always has stacks

- platform/run_image.go
- platform/run_image_test.go
We need to parse the reference in case the registry is not specified (defaults to Docker Hub)
> Improved matching when selecting run image metadata

- cmd/lifecycle/rebaser.go
- detector.go
- internal/encoding/utils.go
- internal/name/ref.go
- platform/files/analyzed.go
- platform/run_image.go
- rebaser.go
- rebaser_test.go
- Fix daemon invocation by trying to read app image after we have a docker client
- Don't do stack validation for images built on newer platforms
> Fixes for rebase and log message improvements

- .github/workflows/build.yml
- golangci.yaml
The goal of this commit is to enforce stricter style, including godoc comments, but only going forward.
For reference, the linters enabled in this commit can be seen running against the current repo here:
https://github.com/buildpacks/lifecycle/actions/runs/5182278788/jobs/9338882119?pr=1110
but by specifying the `new-from-rev` option in golanci.yaml config we're able to say that these should only apply in the future. This functions as a "since" commit,  meaning "the linters only apply to commits since this one."
The soft-agreement of turning this on would be something like:
- the "since" commit is allowed to be bumped forward for large refactors where fixing 10s or 100s of linter errors is an unreasonable additional burden
- new features and bugfixes that incur only a handful of linter …
> turn on additional linter checks including godoc comments

- generator.go
- internal/name/ref.go
- internal/name/ref_test.go
- platform/files/analyzed.go
- platform/files/stack.go
- platform/labels.go
- rebaser.go
- rebaser_test.go
* When deciding whether to update run image metadata, consider the platform API __of the rebaser__ vs the platform API of the previous image
* Warn whenever `--force` (that is provided) is needed to successfully complete the operation
Related discussion: https://github.com/buildpacks/lifecycle/issues/1098#issuecomment-1602849946
> Fixes for rebase

- acceptance/detector_test.go
- acceptance/testdata/restorer/container/layers/some-extend-false-analyzed.toml.placeholder
- acceptance/testdata/restorer/container/layers/some-extend-true-analyzed.toml.placeholder
- analyzer.go
- buildpack/dockerfile.go
- buildpack/dockerfile_test.go
- cmd/lifecycle/analyzer.go
- cmd/lifecycle/detector.go
- cmd/lifecycle/exporter.go
- cmd/lifecycle/restorer.go
- generator.go
- generator_test.go
- handlers.go
- internal/encoding/utils.go
- internal/name/ref.go
- internal/name/ref_test.go
- platform/files/analyzed.go
- platform/files/run.go
- platform/files/stack.go
- platform/resolve_analyze_inputs_test.go
- platform/resolve_create_inputs_test.go
- platform/run_image.go
- platform/run_image_test.go
- platform/target_data.go
- platform/testdata/layers/analyzed-docker.toml
- platform/testdata/layers/analyzed-mirror.toml
- platform/testdata/layers/analyzed-other.toml
- platform/testdata/layers/analyzed.toml
- platform/testdata/layers/run.toml
- platform/testdata/layers/stack.toml
- When pulling remote image data during `restore`, fail if the remote image is not found
- When validating dockerfiles during `generate`, set extend to true if there are any instructions (vs more than one instruction)
- Update matching logic when considering if two image names are equivalent to ignore the digest portion of the reference if present (for the purpose of selecting data from run.toml to add to the lifecycle metadata label during `export` i.e., “run image for rebase”)
- During `export`, continue to use run image identifier (which could be a digest reference or daemon image ID) as the run image reference instead of falling back to image name when exporting to a daemon
- When finding the run image info during `export`, use the run image "image" (name) in analyzed.toml as the …
> Fixes for run image extension

- .github/workflows/check-latest-release.yml
see https://github.com/buildpacks/lifecycle/issues/1021
> adds grype json output to the created github issue

- acceptance/acceptance_test.go
- acceptance/analyzer_test.go
- acceptance/launcher_test.go
- acceptance/phase_test.go
- acceptance/restorer_test.go
- acceptance/testdata/analyzer/Dockerfile
- cmd/apis.go
- cmd/apis_test.go
- platform/defaults.go
- platform/launch/defaults.go
Instead of defaulting to (deprecated) version 0.3
Instead of defaulting to a newer Platform API version, which would silently change behavior for platforms that do not currently set this env var
First PR in support of https://github.com/buildpacks/rfcs/blob/main/text/0110-deprecate-apis.md
> Require the CNB_PLATFORM_API env var to be set

- cmd/lifecycle/cli/command.go
I was tempted to make it a fatal error and exit but honestly someone out there probably has an app called `-minuses-are-cool-characters-to-start-my-app-name-with` or something. 
*before*
```
> ./exporter  apps/bash-script -launcher ../lifecycle/out/darwin-amd64/lifecycle/launcher
```
would result in a bunch of reasonable looking output but end with:
```
ERROR: failed to export: creating launcher layers: failed to stat launcher at path '/cnb/lifecycle/launcher': stat /cnb/lifecycle/launcher: no such file or directory
```
because we put the `-launcher` flag _after_ the app name.  
NOTE that this is much harder to notice if there's several other args, especially if the app-name positional arg is preceded by a boolean flag arg such as `-daemon`. 
*after*
Your stuff will still fail, but …
> warn when a positional argument might have been a flag

- cmd/lifecycle/main.go
before:
```
➜ CNB_PLATFORM_API=0.12 ./out/darwin-amd64/lifecycle/lifecycle -help
ERROR: failed to unknown phase: -help
➜   CNB_PLATFORM_API=0.12 ./out/darwin-amd64/lifecycle/lifecycle creator --help
ERROR: failed to unknown phase: creator
```
after:
```
➜   CNB_PLATFORM_API=0.12 ./out/darwin-amd64/lifecycle/lifecycle creator       
ERROR: failed to recognize phase: creator
Valid phases: detect, analyze, restore, build, export, rebase, create, extend
➜  CNB_PLATFORM_API=0.12 ./out/darwin-amd64/lifecycle/lifecycle --help      
ERROR: failed to recognize phase: --help
Valid phases: detect, analyze, restore, build, export, rebase, create, extend
```
> be more helpful when you dont recognize the phase

- cmd/lifecycle/restorer.go
Report the image name so end-users can take some action.
> Report image name when restorer fails to pull

- Makefile
- darwin.mk
- launcher.mk
- lifecycle.mk
Add build make actions to build lifecycle for MacOS M1 chipset
> Add support for darwin-arm64 chipset

- cmd/lifecycle/restorer.go
- image/layout_handler.go
- image/layout_handler_test.go
This PR adds the `layout` and `layout-dir` flags to the `restorer` phase when the PLATFORM_API version is equal or greater than 0.12.
It also fixes an issue when the `run-image` is read from the analyzed.toml file we will get something like:
```json
{
"Reference":"",
"Image":"/layout-repo/index.docker.io/cnbs/sample-stack-run/jammy",
"Extend":false,
"target":{
"os":"linux",
"arch":"amd64"
}
}
```
We were trying to parse the `Reference.Image` into a path, but it is already a path, so we don't need to do anything in that case.
When using platform API `0.12` or greater, The layout flags  `layout` and `layout-dir` were exposed in the `restorer` binary 
---
Resolves #1194 
---
> Adding missing flags for OCI Layout to restorer

- .github/workflows/build.yml
Pack acceptance has been failing since https://github.com/buildpacks/lifecycle/pull/1182 because we weren't looking for the go.mod file in the right place.
> Fix setup-go by looking for go.mod within pack directory

- .github/dependabot.yml
- .github/workflows/build.yml
- .github/workflows/check-latest-release.yml
- .github/workflows/draft-release.yml
- .github/workflows/post-release.yml
> Update some actions and configure dependabot to update actions

- cmd/lifecycle/analyzer.go
- cmd/lifecycle/creator.go
- cmd/lifecycle/detector.go
- cmd/lifecycle/exporter.go
- cmd/lifecycle/extender.go
- phase/analyzer.go
- phase/analyzer_test.go
- phase/connected_factory.go
- phase/detector.go
- phase/detector_test.go
- phase/extender.go
- phase/extender_test.go
- phase/generator.go
- phase/generator_test.go
- phase/handlers.go
- phase/hermetic_factory.go
- phase/testmock/config_handler.go
- platform/platform.go
This PR builds off of https://github.com/buildpacks/lifecycle/pull/1205 to change lifecycle "factories" (for the phases that use them) to use `platform.LifecycleInputs` instead of a long list of arguments. This will pave the way for us adding factories for the other phases later.
Refactor: lifecycle phase factories
> Refactor lifecycle phase factories

- acceptance/restorer_test.go
- acceptance/testdata/restorer/container/layers/group.toml
- acceptance/testdata/restorer/container/layers/some-extend-false-analyzed.toml.placeholder
- cmd/lifecycle/restorer.go
- phase/generator.go
- phase/generator_test.go
In lifecycle 0.17.0 we stopped writing `reference` in analyzed.toml during the generate phase when the run image was switched by extensions. This is because the restorer would "always" take the run image `image` and turn it into a `reference`. However the restorer was only doing this for Platform API 0.12 and above.
`[run-image.image]` isn't a thing in Platform API 0.10 so we have to write the image from extensions into `reference` and overwrite it with a real reference during restore.
Fixes regression in Platform API 0.10 by writing `reference` in analyzed.toml during the generate phase when the run image was switched by extensions
---
Resolves #___
---
> Fix regression in Platform API 0.10

- auth/keychain.go
- auth/keychain_test.go
- go.mod
- go.sum
When reading the keychain from the environment in order, the registry were taken exactly as specified. This resulted in some cases where the credentials were not found and required the user to specify exactly the expected format although `docker pull` worked with the same credentials.
Fixes access of url based repositories for specific cases.
---
Resolves #___
---
Example that did not work:
```json
{
"auths": {
"https://index.docker.io/v1/": {
"auth": "..."
}
}
}
```
> Fix usage of URL based registries

- log/timelog_test.go
- platform/resolve_analyze_inputs_test.go
- platform/resolve_create_inputs_test.go
- platform/resolve_inputs.go
- platform/run_image.go
- platform/run_image_test.go
When the lifecycle failed because there was no readable run image, the error was rather misleading:
`-run-image is required when there is no stack metadata available`
This was caused by hiding the underlying error.
Improve error message in case run-image is not readable.
---
Resolves #___
---
When the run image is on a protected registry, the `auth` data must be provided to the lifecycle.
> Do not obscure error message

- .github/workflows/check-latest-release.yml
Our check-release workflow has been [failing](https://github.com/buildpacks/lifecycle/actions/runs/6687443320/job/18168086995#step:8:34) with errors such as `HTTP 403: Resource not accessible by integration (https://api.github.com/repos/buildpacks/lifecycle/labels)`. I think it is because the default permissions for GITHUB_TOKEN are too restrictive. 
n/a
> Fix check release workflow by giving write permissions to the token

- log/timelog.go
- log/timelog_test.go
- phase/cache_test.go
- phase/save.go
The default of emitting timings to info is too noisy.  This change lets platforms that want to see timings do so by setting the log level to debug.
- `lifecycle` now only emits timing to the debug logs.
---
https://cloud-native.slack.com/archives/C0331B5QS02/p1698686716010529
> Print `Timer` logs in debug mode only

- .github/dependabot.yml
Go minor/patch dependencies will now be grouped, using the new Dependabot grouping feature:
https://github.blog/changelog/2023-08-17-grouped-version-updates-by-semantic-version-level-for-dependabot/
Major updates, as well as security updates will still be opened as separate PRs. I've not grouped GitHub Actions update PRs, since the volume is typically much lower for those.
The custom open pull requests limit has been removed, since it is no longer necessary, as there won't be as many open PRs.
In addition, the schedule has been changed from daily to weekly.
This reduces project maintenance toil (no more having to manually create combined update PRs), plus makes it less painful for contributors to subscribe to repository notifications (currently there is a lot of noise from Dependabot PRs …
> Group minor/patch version Go Dependabot updates into one PR

- acceptance/creator_test.go
- acceptance/testdata/creator/container/cnb/extensions/samples_hello-world/0.0.1/extension.toml
- acceptance/testdata/creator/container/cnb/order-with-extensions.toml
- cmd/lifecycle/creator.go
Previously, if a platform provided an order.toml containing extensions, the creator would error due to "missing extensions directory". Now, the creator will actually run detect on the order and error with a "not supported" message if the detected group contains extensions, proceeding otherwise. 
This will allow builders to contain extensions and builds to succeed if the contained extensions do not detect by default (see https://github.com/buildpacks/community/discussions/244).
Creator errors if detected order contains extensions
---
Resolves https://github.com/buildpacks/lifecycle/issues/1241
> Creator errors if detected order contains extensions

- acceptance/exporter_test.go
- cmd/lifecycle/cli/flags.go
- cmd/lifecycle/creator.go
- cmd/lifecycle/exporter.go
- layers/factory.go
- platform/defaults.go
- platform/lifecycle_inputs.go
- platform/resolve_create_inputs_test.go
- platform/resolve_inputs.go
Export cache image and app image in parallel when parallel-export is enabled by platform.
Export cache image and app image in parallel when parallel-export is enabled by platform.
---
Resolves # 1167 
---
Export cache image and app image in parallel when parallel-export is enabled by platform.
cc - credits Woa [me@wuzy.cn](mailto:me@wuzy.cn) for initiating this work
> Export app image and cache image in parallel

- phase/extender.go
Adds debug statements to the extender
Adds debug statements to the extender
> Add debug statements to the extender

- phase/extender_test.go
Refactor `phase/extender_test.go` as suggested in https://github.com/buildpacks/lifecycle/pull/1276#discussion_r1489675972
In #1276 we duplicated most of the test code in `phase/extender_test.go`, basically doing the same tests twice, once for Platform API `0.12` and once for `0.13`. The API versions expect a different folder layout, which requires changes to the test setup. The reduce the size of `phase/extender_test.go`, I:
- moved the code to create the folder layout into a helper function (it will check for the Platform API version and behave differently based on that)
- added a loop around the test cases looping over API versions.
Now we have every tests only once in code, while still being executed twice.
The drawback: The helper function is quite complex (especially for test code). …
> refactor `phase/extender_test.go`

- cmd/lifecycle/cli/flags.go
When looking at the flags for `rebase`, it is confusing because both `-image` and `-run-image` are documented as `reference to run image`. It's not until inspection of the source code that you realize `-image` is deprecated. This adds a `[deprecated]` marker to `-image` so it can be seen in the help output.
Looking at uses of `DeprecatedFlagRunImage`, this impacts both `rebase` and `export`.
Document `-image` flag as deprecated in help output for `rebase` and `export`.
> Document deprecatedRunImage as deprecated

- cmd/lifecycle/rebaser.go
- platform/run_image.go
- platform/run_image_test.go
Currently, if `-run-image` is not set, `io.buildpacks.lifecycle.metdata[runImage.reference]` is used. This does not follow the [Run Image Resolution spec](https://github.com/buildpacks/spec/blob/main/platform.md#run-image-resolution), which specifies using `io.buildpacks.lifecycle.metdata[runImage.image]` and optionally `io.buildpacks.lifecycle.metdata[runImage.mirrors]`. Because of this, it ends up making `lifecycle rebase` without the `-run-image` flag a no-op because the run image is pinned to the same version instead of getting the latest.
This change simplifies and unifies the behavior for before and after Platform Version 0.12 so that they both read the same run-image data type (just from different locations), and then validate and resolve mirrors the same.
Note, this is also …
> Fix rebase run-image resolution

- phase/generator_test.go
Refactor `phase/generator_test.go` as suggested in https://github.com/buildpacks/lifecycle/pull/1276#discussion_r1489634499.
Related PR #1297
In #1276 we duplicated some of the test code in `phase/generator_test.go`, basically doing the same tests twice, once for Platform API `0.12` and once for `0.13`. The API versions expect a different folder layout, which requires changes to the test setup and assertions. The reduce the size of `phase/generator_test.go`, we:
- added a loop around the test cases looping over API versions.
- for API version >= 0.13 skip the copy tests
- added some `platformAPI.AtLeast("0.13")` switches where file paths are different
Now we have every tests only once in code, while still being executed twice (even the ones that we previously only had for platform API …
> refactor `phase/generator_test.go`

- phase/extender.go
(in addition to the original top layer digest) to determine what is an extension layer and what is an original layer.
Relying on the original top layer digest (only) introduced errors if the original run image had a duplicated top layer.
Fixes https://github.com/buildpacks/lifecycle/issues/1300
Uses the original layer count (in addition to the original top layer digest) to determine what is an extension layer and what is an original layer.
Fixes issue where the `extender` fails to copy extension layers when the original run image has a duplicated top layer
---
Resolves https://github.com/buildpacks/lifecycle/issues/1300
---
I looked into unit testing this, but decided it wasn't worth it
> When copying extended run image layers, use the original layer count

- buildpack/build.go
- buildpack/detect.go
- buildpack/generate.go
- env/build.go
- env/build_test.go
- phase/builder.go
- phase/builder_test.go
- phase/detector.go
- phase/detector_test.go
- phase/generator.go
- phase/generator_test.go
- platform/run_image_test.go
- platform/target_data.go
when the Buildpack API version is at least 0.10
Previously, we only set these variables when the Platform API version was at least 0.12. But, newer Buildpack APIs expect these variables regardless of the Platform API version. If we are on an older platform, derive the target variables from the base image OS.
The lifecycle always set CNB_TARGET_* variables during detect, build, and generate when the Buildpack API version is at least 0.10
---
Resolves #1308 and #1186
---
> Always set CNB_TARGET_* variables during detect, build, and generate

- .github/workflows/post-release.yml
Our post release workflow failed for 0.19.0-rc.2: https://github.com/buildpacks/lifecycle/actions/runs/8160849428
Someday, I'd like to modularize our setup to make it easier to just add os/arch combinations that we want to support as some kind of string array. But, that day is not today.
---
Tested on fork: https://github.com/natalieparellano/lifecycle/actions/runs/8175675694
> Fix post release workflow by calculating sha for linux-ppc64le

- cmd/lifecycle/analyzer.go
- cmd/lifecycle/builder.go
- cmd/lifecycle/cli/command.go
- cmd/lifecycle/cli/flags.go
- cmd/lifecycle/creator.go
- cmd/lifecycle/detector.go
- cmd/lifecycle/exporter.go
- cmd/lifecycle/extender.go
- cmd/lifecycle/rebaser.go
- cmd/lifecycle/restorer.go
- platform/lifecycle_inputs.go
Currently, log level and color level are only configurable via flags (`-log-level` and `-no-color`).
This broke awhile back in an effort to consolidate some logic in the `platform` package.
Log level and color level are configurable via the environment (in addition to flags)
---
> Fix: log level and color level should be configurable via the env

- api/apis.go
Fixes https://github.com/buildpacks/lifecycle/issues/1322
lifecycle 0.19.0 "supports" Buildpack API 0.11 in that it is possible to use Buildpack API 0.11 features with this lifecycle, but it doesn't declare support for this API version in `api.Buildpack` nor in lifecycle.toml and the associated label. This fix adds Buildpack API 0.11 as a supported API version.
Adds Buildpack API 0.11 as a supported API version
---
Resolves #1322
> Buildpack API 0.11 is supported as of lifecycle 0.19

- auth/README.md
- auth/keychain.go
Vendor keychains can be slow or fail. This allows platform operators to skip them entirely.
Allow platform operators the ability to skip vendor specific keychain implementations by setting `CNB_REGISTRY_AUTH_KEYCHAIN_SKIP_AMAZON` or `CNB_REGISTRY_AUTH_KEYCHAIN_SKIP_AZURE`.
---
Resolves https://github.com/buildpacks/lifecycle/issues/1007#issuecomment-1561349524
---
The Amazon/ECR one is _terribly_ inefficient. It tries to query the metadata service and eventually fails after a few tries. This is not needed if the platform is providing the credentials via Default/Env. Selectively disabling seemed liked a decent enough idea.
> Allow env vars to skip vendor specific keychain

- .github/workflows/draft-release.yml
We are getting warnings about go-version not being specified. This should fix that.
https://github.com/buildpacks/lifecycle/actions/runs/8573689482/job/23499317720#step:11:12
I'll cherry pick this to release/0.19.2 to fix the workflow there as well.
N/A
---
N/A
---
N/A
> Add go-version-file to draft-release workflow

- phase/restorer.go
Initialize default `layer.LayerMetadataRestorer` and `layer.SBOMRestorer` structs if none provided.
---
Resolves #___
---
At the moment, it is impossible to reuse `phase.Restorer` structure due to the usage of two internal structs: `layer.LayerMetadataRestorer` and `layer.SBOMRestorer`. Defaulting them with the default constructors would allow re-use of the `phase.Restorer` without opening up the internal package.
This change would greatly improve future work on https://github.com/cloudfoundry/community/pull/796
> Initialize default `LayerMetadataRestorer` and `SBOMRestorer` if none provided

- platform/target_data.go
- platform/target_data_test.go
Fixes https://github.com/buildpacks/lifecycle/issues/1337
The lifecycle, when determining if a base image satisfies target constraints declared by a buildpack, fails if the buildpack declares distro information but the base image does not (fixes spec compliance)
---
Resolves #1337
---
> When a buildpack declares distro information, but a base image does not, consider it not a match

- phase/builder.go
- phase/builder_test.go
- phase/detector.go
- phase/detector_test.go
- phase/generator.go
- phase/generator_test.go
- platform/run_image_test.go
- platform/target_data.go
Related issue: https://github.com/buildpacks/lifecycle/issues/1336
---
Resolves #1336
---
> Read `/etc/os-release` file when distro information is not present in labels

- phase/analyzer.go
- phase/analyzer_test.go
- phase/detector.go
- platform/run_image_test.go
- platform/target_data.go
- platform/target_data_test.go
This will fix an issue reported by our friends from Paketo. Without this fallback, when combined with the stricter validation in https://github.com/buildpacks/lifecycle/pull/1348, we could fail builds that we actually want to proceed with.
https://github.com/buildpacks/lifecycle/pull/1347 reads the file when providing target env vars to buildpacks during detect, but we also need to consider this info when deciding whether or not to run detect for the buildpack.
The `detector`, when determining if a base image satisfies target constraints declared by a buildpack, also uses information from `/etc/os-release` when distro information is not present in the run image labels
---
Resolves #___
---
I moved some functions around in files, so ignore the first commit when parsing the diff (it just …
> Also read distro information from /etc/os-release when checking target compat

- acceptance/testdata/detector/Dockerfile
- acceptance/testdata/detector/container/cnb/buildpacks/simple_buildpack/simple_buildpack_version/bin/detect
- acceptance/testdata/detector/container/cnb/buildpacks/simple_buildpack/simple_buildpack_version/buildpack.toml
- buildpack/bp_descriptor.go
- buildpack/bp_descriptor_test.go
- buildpack/testdata/buildpack/by-id/B/v1.2/buildpack.toml
- buildpack/testdata/buildpack/by-id/B/v1.star/buildpack.toml
- buildpack/testdata/buildpack/by-id/B/v2.2/buildpack.toml
- buildpack/testdata/buildpack/by-id/B/v2.star/buildpack.toml
- phase/detector.go
- platform/target_data.go
- platform/target_data_test.go
- If a buildpack does not specify targets, but DOES specify stack with ID io.buildpacks.stacks.bionic, only translate that to a target if the buildpack is on a newer Buildpack API (where stacks are deprecated, and we expect targets) OR if the buildpack only ever declared one stack. When multiple stacks are declared, specifying only one target actually reduces the number of builds that can succeed. Older Buildpack APIs don't actually specify stack -> target translation so we should do the thing that will work in the maximum number of builds.
- If a buildpack fails to specify os/arch (but specifies distro) still check targets
- If the run image fails to specify os/arch (this should not happen actually as we will fail during analyze) still check targets
- Fix typo in buildpack descriptor …
> More fixes for target compat checking during detect

- api/apis.go
- cmd/lifecycle/restorer.go
- internal/layer/metadata_restorer.go
- internal/layer/metadata_restorer_test.go
- internal/layer/testdata/cache_metadata.json
- phase/restorer.go
- phase/restorer_test.go
In case if a layer is found in cache and marked as `launch = true` and `cache = true`, it will be restored if not found in the `appLayers`.
This case is possible if `-previous-image` is not set/found, however a `-cache-dir` is provided (backed by persistent volumes etc.)
---
Resolves #___
---
> Restore cached launch layers not found in `appLayers`

- phase/builder_test.go
- phase/detector_test.go
- phase/generator_test.go
- platform/target_data.go
- platform/target_data_test.go
Fixes https://github.com/buildpacks/lifecycle/issues/1371
When populating target data for older platforms, populate OS & architecture as well as distro information
---
Resolves #1371
---
> Fix CNB_TARGET_* env vars on older Platform API

- acceptance/analyzer_test.go
- image/registry_handler.go
When permissions issues are encountered, it can be hard to determine the root cause without the error returned from the registry
The lifecycle surfaces error from registry (when it fails to verify image permissions) as an error instead of a debug message
---
Resolves #___
---
> Surface registry error

- cache/caching_image_test.go
- cache/common.go
- cache/image_cache.go
- cache/image_cache_test.go
- cache/image_deleter.go
- cache/volume_cache.go
- cache/volume_cache_test.go
- cmd/lifecycle/exporter.go
- cmd/lifecycle/main.go
- internal/layer/sbom_restorer_test.go
- phase/analyzer.go
- phase/analyzer_test.go
- phase/cache.go
- phase/cache_test.go
- phase/connected_factory.go
- phase/exporter.go
- phase/restorer.go
- phase/restorer_test.go
- phase/testmock/cache/image_deleter.go
Fixes https://github.com/buildpacks/lifecycle/issues/1380
* The lifecycle, when encountering cache metadata for a layer that does not exist in the cache, will skip over the layer instead of failing the build
---
Resolves #___
---
> Recover corrupted cache

- cmd/lifecycle/restorer.go
Fixes the result of a run-image read access check introduced in https://github.com/buildpacks/lifecycle/pull/1364
The actually accessible run-image was never used, making the stage to fail if the previous image is not accessible
---
Resolves #___
---
> Fix run-image access check in restorer phase

- buildpack/build.go
When setting up buildpack env, process layers for a given buildpack in alphabetical order
When setting up buildpack env, process layers for a given buildpack in alphabetical order
---
Resolves #1393
---
> When setting up buildpack env, process layers for a given buildpack in alphabetical order

- phase/exporter.go
- phase/exporter_test.go
The 1/N app layer logs are emitted _after_ the layers have been added. This can sometimes be an expensive operation depending on the layer size and export target.
When trying to understand performance during builds, this wording implies the previous log line before the app layers was responsible for the time between the log lines. Adjusting the wording will make it a bit clearer that the time between the two log lines includes both steps.
Before:
```bash
03:50:00 Adding layer 'buildpacksio/lifecycle:launch.sbom'
03:51:00 Adding 5/5 app layer(s)
````
After:
```bash
03:50:00 Adding layer 'buildpacksio/lifecycle:launch.sbom'
03:51:00 Added 5/5 app layer(s)
````
Adjust exporter App Layer log output
---
If we are more interested in going the other direction, where we keep "Adding 1/N app …
> Adjust exporter App Layer log output

- .github/workflows/build.yml
Bump upload and download actions to v4 to avoid deprecation affecting our pipelines.
- chore: Bump upload and download github actions to v4 to avoid deprecation affecting our pipelines.
---
Closes https://github.com/buildpacks/lifecycle/pull/1260
Closes https://github.com/buildpacks/lifecycle/pull/1261
---
Seems as though the limitations we ran into initially have been removed or increased.
> bump upload-artifacts-action

- .grype.yaml
This is the same CVE [here](https://github.com/buildpacks/lifecycle/pull/1415/files) but by another identifier.
---
---
grype was failing when I was trying to cut a new minor patch release.
> Silence non-impactful CVE - GHSA-v23v-6jw2-98fq

- internal/fsutil/os_detection.go
- internal/fsutil/os_detection_linux_test.go
- internal/fsutil/os_detection_notlinux_test.go
- internal/fsutil/os_detection_test.go
- phase/builder.go
- phase/detector.go
- phase/generator.go
- platform/run_image.go
- platform/target_data.go
- platform/target_data_test.go
When the run image does NOT have `io.buildpacks.base.distro.name` or `io.buildpacks.base.distro.version` labels:
We're currently emitting an info message `"target distro name/version labels not found, reading /etc/os-release file"` every time we call `GetTargetOSFromFileSystem` - which happens a LOT, especially during the detect phase. We do this:
* For every buildpack, for every target that the buildpack declares, until we find a target that matches the base image
* For every buildpack, when we run ./bin/detect
This is very noisy, and annoying because it isn't information that buildpack authors need. We should only log the message once, so that platform operators / builder creators can see that the run image needs to be updated with a label.
The lifecycle only logs once (per phase) when …
> Only log once (per phase) when we have to get target distro information from /etc/os-release

- cmd/lifecycle/exporter.go
> Fix issues/1425 by providing insecure registries when we access the run image

- acceptance/creator_test.go
- acceptance/detector_test.go
- acceptance/exporter_test.go
- acceptance/extender_test.go
- acceptance/rebaser_test.go
- acceptance/restorer_test.go
- acceptance/testdata/launcher/exec.d/fd_unix.go
- acceptance/variables_unix.go
- archive/tar_unix.go
- internal/fsutil/os_detection_linux_test.go
- internal/fsutil/os_detection_notlinux_test.go
- internal/path/defaults_unix.go
- launch/exec_d_unix.go
- launch/launcher_unix.go
- launch/testdata/cmd/execd/fd_unix.go
- launch/testhelpers/syscall_unix.go
- launch/testhelpers/syscall_windows.go
- layers/layers_unix_test.go
- priv/sock_unix.go
- priv/user_linux.go
- testhelpers/vars_darwin.go
- testhelpers/vars_linux.go
Get rid of obsolete `// +build` lines that are deprecated.
https://tip.golang.org/doc/go1.18#go-build-lines
Kind of related: #1271
I'm working on getting support for `FreeBSD`. This patch helps to simplify the code base so that the diff for FreeBSD support gets smaller.
> Remove obsolete // +build lines

- lifecycle.mk
The `lifecycle.mk` file is missing the creator and extender symlinks.
#1171
> lifecycle.mk: Add creater and extender symlinks

- internal/extend/kaniko/dockerfile_applier_unix.go
- priv/user_unix.go
Make it possible to compile `lifecycle` and `launcher` for FreeBSD.
- #1271 
- #1087 
It 'just compiles' for FreeBSD. That's it :-) Other functionality can be added afterwards (priv/user.go functionality, maybe tests, correct launch/bash.go to use /usr/local/bin/bash and others).
If you would want to test the build phase under Linux or macOS for example:
- git checkout the branch for this PR
- git cherry-pick c813b1c1366f05a756f77a44da0121c21ca8316e from https://github.com/buildpacks/lifecycle/pull/1438
- apply the following patch
```diff
diff --git a/Makefile b/Makefile
index 2501de30..b77141ea 100644
--- a/Makefile
+++ b/Makefile
@@ -39,9 +39,9 @@ GOFILES := $(shell $(GOCMD) run tools$/lister$/main.go)
all: test build package
-GOOS_ARCHS = linux/amd64 linux/arm64 linux/ppc64le …
```
> Support FreeBSD build phase

- go.mod
- go.sum
Picked version updates from #1440 that are working.
It looks like the go-dependencies buildkit, docker are blocked by GoogleContainerTools/kaniko, therefore I've picked the versions that can be upgraded right away.
> Bump go-dependencies containerd, golang.org/x/sync and golang.org/x/sys

- Makefile
Use a Makefile function to create dynamic build targets so it's simple to add new GOOS/GOARCH combinations if required. The duplication of Makefile code is reduced.
#1171 
My 'overall goal' is still to get some FreeBSD support as attempted in #1271 and #1087 .
I thought it might make sense to help out with #1171 and come up with a simpler Makefile so that other GOOS/GOARCH can be added more easily. I'm not a Makefile expert.
I've left windows out since it might get removed soon.
I've left out the darwin build targets for the time being.
Other Makefile targets like the package targets can be implemented in a similar way once this attempt is accepted of being worth it.
I wonder (and this contradicts this attempt in this PR) whether the Makefile should just work with GOOS and GOARCH set …
> Makefile: Create dynamic build targets

- acceptance/phase_test.go
This change adds a thread sleep at a spot in our unit tests were we identified some flappiness. This change will help ensure our time-sensitive tests fail less often.
---
Here's an [example](https://github.com/buildpacks/lifecycle/actions/runs/13247050519/job/37034661620) of failing tests this PR addresses.
> Add logging and sleep to tests

- acceptance/exporter_test.go
I think we are seeing flappy tests due to the potential for the registry and daemon case sharing the same variable. Lets duplicate the variable to remove the potential and do the cleanup in each test when block.
> Remove potential for exporter_test race
