cmd/detector/main.go, detector.go, detector_test.go, map_test.go
I ran into some panics when trying to implement an `order.toml`. I think this will cause it to fail more gracefully.
=> Improvements to detector

cmd/exporter/main.go
Makes use of the new env var added in https://github.com/buildpack/packs/pull/20
=> Parameterize stackTag for exporter

images/build/Dockerfile, images/run/Dockerfile
Updates to work with the spec changes
=> Bug fixes in images/build/Dockerfile

Dockerfile, cmd/analyzer/main.go, cmd/builder/main.go, cmd/cmd.go, cmd/detector/main.go, cmd/exporter/main.go, cmd/launcher/main.go, exporter.go, exporter_test.go, images/build/Dockerfile, images/run/Dockerfile, images/util/Dockerfile, img/actions.go, launcher.go, launcher_test.go, lifecycle.go, metadata.go
* PACK_USER_ID and PACK_GROUP_ID defaults are still provided with stack env vars
[buildpack/roadmap#14]
=> Uses hardcoded defaults for most lifecycle inputs

cmd/cmd.go
=> Restores default run image

image/factory.go, image/local.go
Fixes https://github.com/buildpack/pack/issues/74
Implementation from https://github.com/buildpack/pack/pull/78
=> Allows docker pull of private images

images/build/Dockerfile
=> Adds docker credential helpers to build image

cmd/cmd.go, cmd/exporter/main.go, exporter.go, exporter_test.go, fs/tar.go, fs/tar_test.go, testhelpers/test_image.go, testhelpers/testhelpers.go
Fixes https://github.com/buildpack/pack/issues/80
=> Remove layers-src and app-src exporter params

images/bin/build, images/samples/Dockerfile
=> Samples Builder Image encodes runImage in label

image/remote.go, image/remote_test.go
=> Saved remote images have accurate createdAt timestamp

detector.go, exporter.go, exporter_test.go, map_test.go
=> Ensure buildpack versions are written to app image metadata

go.mod, go.sum
Part 1 of fixing buildpack/pack#102. Need to update the pack CLI as well.
=> Update docker dependency

.travis.yml
=> Avoid building images for PRs

cmd/analyzer/main.go, cmd/cacher/main.go, cmd/detector/main.go, cmd/exporter/main.go, cmd/restorer/main.go
=> removes timestamps from lifecycle logs

image/local.go
* when new image is built from different base, don't assume you can reuse layers without fetching the layer tar
=> Fixes issues that occurs in some local image rebuilds

cmd/cmd.go, cmd/exporter/main.go, exporter.go, exporter_test.go, images/samples/Dockerfile, metadata.go
* Remove label flag from exporter
=> Export stack metadata from stack.toml

Dockerfile, images/build/Dockerfile
=> dev stack images have new default dirs with correct ownership

testhelpers/test_image.go
=> Implement rebase in image fake

cacher_test.go, exporter_test.go, image/fakes/image.go, image/testhelpers/fake_image.go, restorer_test.go
=> Move fake image under image package

image/fakes/image.go, image/image.go, image/local.go, image/local_test.go, image/remote.go, image/remote_test.go, testmock/image.go
This gives us access to the CreatedAt time of an image
=> Add CreatedAt on Image interface

analyzer_test.go, cache/image_cache_test.go, exporter_test.go, go.mod, go.sum, vendor/github.com/buildpack/imgutil/fakes/image.go, vendor/github.com/buildpack/imgutil/local.go, vendor/github.com/buildpack/imgutil/remote.go, vendor/modules.txt
=> Bump imgutil

cmd/cmd.go, cmd/launcher/main.go
- Keep backwards-compatible for now
Resolves #141
=> Look for CNB_PROCESS_TYPE instead of PACK_PROCESS_TYPE

Makefile
=> Fix version output when using -version flag

Makefile, acceptance/acceptance_test.go, cmd/cmd.go, cmd/exporter/main.go, exporter.go, exporter_test.go, metadata/build.go
=> Add launcher metadata to build metadata label

Makefile, acceptance/acceptance_test.go, cmd/cmd.go, cmd/exporter/main.go, exporter.go, exporter_test.go, metadata/build.go
=> Add launcher metadata to build metadata label.

Makefile
=> Adds lifecycle.toml to package

layers.go
=> remove layer map so order is deterministic

Makefile
By stripping down debug information
Signed-off-by: David Gageot <david@gageot.net>
=> Produce smaller binaries

analyzer_test.go, archive/tar_test.go, cache/image_cache_test.go, cache/volume_cache_test.go, compat/compat_test.go, golangci.yaml, internal/logging/logging_test.go
Also restore the check on imports being organised
in 3 groups.
Signed-off-by: David Gageot <david@gageot.net>
=> Add more linters

Makefile
=> Add missing directory when building

cache/volume_cache.go, cache/volume_cache_test.go
=> VolumeCache handles duplicate layers

cmd/exporter/main.go
This matches analyzer and restorer.
Signed-off-by: Lukas Berger <bergerl@google.com>
=> Simplify creating cache in exporter

README.md
* fixes other outdated README content
=> Adds API versions to README

CODEOWNERS
=> Adds CODEOWNERS

analyzer.go
=> info rather than warn when previous image not found

layers.go
=> sort buildpack layers during export to ensure consistent ordering

exporter_test.go, project_metadata.go
=> io.buildpacks.project -> io.buildpacks.project.metdata

README.md, analyzer.go, analyzer_test.go, exporter.go, exporter_test.go, layers.go, metadata.go, restorer.go, testdata/analyzer/app_metadata.json, utils.go
=> store.toml

Makefile, analyzer.go, builder.go, builder_test.go, buildpack.go, cmd/launcher/main.go, cmd/lifecycle/builder.go, exporter.go, launch/launch.go, launch/launcher.go, launch/launcher_test.go, layers.go, metadata.go, restorer.go, utils.go
Addresses #247:
``` 
opal:lifecycle stephen$ du -h out/lifecycle/launcher
2.2M	out/lifecycle/launcher
```
=> Refactor launcher to remove dependency on github.com/docker/docker

.github/workflows/build.yml, cmd/flags.go
=> Register creator -skip-restore flag correctly

go.mod, go.sum
* bumps to a version imgutil that uses a faster compression algorithm
=> faster compression for remote layers

cmd/lifecycle/creator.go, cmd/logs.go, go.mod, go.sum
* Resolves #299
* style changed to match pack phases
=> creator prints colored phase markers

acceptance/launcher_test.go, env/build.go, env/build_test.go, env/launch.go, env/launch_test.go
Resolves #314
Signed-off-by: Simon Jones <simonjones@vmware.com>
=> Adopt race-neutral terminology

cmd/command.go, cmd/flags.go
Issue: #312
I wasn't entirely sure how best to test this. I am happy to add one anywhere someone suggests tho!
=> Add -no-color flag

exporter.go, layers/dir.go, layers/dir_test.go, layers/slices.go
* Also fixes cache log messages
=> Fixes tar reuse logic

builder.go, exporter.go, exporter_test.go, metadata.go, testdata/exporter/previous-image-exists/layers/config/metadata.toml
* Log added labels
* Resolves #321
=> Add buildpack-provided labels to the image

cmd/flags.go, cmd/lifecycle/exporter.go, cmd/lifecycle/rebaser.go, exporter.go, exporter_test.go, go.mod, go.sum, rebaser.go, rebaser_test.go, save.go
* Also, alphabetize some things
Resolves #333
=> exporter and rebaser output a report.toml file

cmd/lifecycle/creator.go
Adds missing `report.toml` config to creator
=> Adds -report flag to creator

.github/workflows/lifecycle-image.yml, tools/go.mod, tools/go.sum, tools/image/main.go
Tested here: https://github.com/natalieparellano/lifecycle/actions/runs/196468263
It created the images here: https://hub.docker.com/repository/docker/natalieparellano/lifecycle/tags?page=1
Tested them out on both platforms, they work :)
=> Build lifecycle image for Windows and create manifest list

builder.go, builder_test.go, buildpack.go, detector.go, detector_test.go
Fixes https://github.com/buildpacks/lifecycle/issues/330
=> Remove top level version

lifecycle.toml
=> Update lifeycle toml

cache.go, cache_test.go, exporter.go, exporter_test.go, go.sum, testdata/cacher/invalid-layers/buildpack.id/layer-1.toml, testdata/cacher/invalid-layers/buildpack.id/layer-2.toml
=> Warn and continue when cached layer has no contents

detector.go
I found the mixture of strings and `error`s that start with `err` in the detector logic to be confusing, so I moved the format strings back into their contexts. If we want to extract format strings more generally, happy to discuss that. This seems more consistent with how they are used in the rest of the file.
=> Clean up error list in detector

README.md, RELEASE.md
=> Add release documentation

builder.go, builder_test.go, cmd/command.go, cmd/lifecycle/builder.go, cmd/logs.go
=> -no-color strips color from buidpack logs

.github/workflows/build.yml
=> Builds windows artifacts on linux

.github/workflows/build.yml
* Removes unecessary 'Set up go env' steps
=> Fix artifact paths in GHA

.github/workflows/build.yml, .github/workflows/draft-release.yml, .github/workflows/post-release.yml
=> Update GitHub Actions workflows to use environment files

README.md
=> Adds API version support table to README

go.mod, go.sum, tools/go.mod, tools/go.sum
=> Bump imgutil to version with newest ggcr release

acceptance/testdata/launcher/posix/container/other-layers/config/metadata.toml, acceptance/testdata/launcher/windows/container/other-layers/config/metadata.toml, builder.go, builder_test.go, env/build.go, env/env.go, env/env_test.go, env/launch.go, env/vars.go, go.sum, launch/launcher.go, launch/launcher_test.go, launch/shell.go, launch/testmock/launch_env.go, testmock/env.go, tools/go.mod, tools/go.sum
* Applies to buildpacks with API 0.5+
=> Changes default env file action to override

.gitignore, acceptance/analyzer_test.go, acceptance/testdata/analyzer/analyze-image/Dockerfile, analyzer.go, auth/env_keychain.go, auth/env_keychain_test.go, cache.go, cache/image_cache.go, cache/volume_cache.go, cmd/flags.go, cmd/lifecycle/analyzer.go, cmd/lifecycle/creator.go, cmd/lifecycle/exporter.go, cmd/lifecycle/main.go, cmd/lifecycle/rebaser.go, cmd/lifecycle/restorer.go, exporter.go, restorer.go, testhelpers/docker.go, testhelpers/testhelpers.go
Fixes #339
Is an alternative to #405
=> Resolve auth before dropping privileges

go.mod, go.sum, tools/go.mod, tools/go.sum
context: https://github.com/buildpacks/imgutil/pull/83
=> Pulls in imgutil fix for podman compat

exporter.go, exporter_test.go
Refs buildpacks/rfcs#134
Signed-off-by: Jose Diaz-Gonzalez <jose@seatgeek.com>
=> feat: set working directory on built image

RELEASE.md, go.sum, tools/go.mod, tools/go.sum
=> Add more info to release page

exporter_test.go, save.go
Resolves: https://github.com/buildpacks/lifecycle/issues/500
=> Add output before saving image during export to indicate progress

acceptance/acceptance_test.go, acceptance/analyzer_test.go, acceptance/detector_test.go, acceptance/launcher_test.go, acceptance/restorer_test.go, cmd/exit.go, cmd/launcher/main.go, cmd/lifecycle/analyzer.go, cmd/lifecycle/builder.go, cmd/lifecycle/creator.go, cmd/lifecycle/detector.go, cmd/lifecycle/exporter.go, cmd/lifecycle/main.go, cmd/lifecycle/rebaser.go, cmd/lifecycle/restorer.go, go.sum, platform/platform.go, platform/v05/exit.go, platform/v05/platform.go, platform/v06/exit.go, platform/v06/platform.go
Pending spec PR: https://github.com/buildpacks/spec/pull/196
=> Condense exit codes

.github/workflows/build.yml, Makefile, README.md, codecov.yml
Tested on fork: https://github.com/natalieparellano/lifecycle/actions/runs/724102070
I am not sure about the thresholds. We'll probably want to play around with them to see what makes sense for lifecycle.
=> Add codecov

.github/ISSUE_TEMPLATE/chore.md, .github/ISSUE_TEMPLATE/feature.md
=> Add chore and feature templates

acceptance/analyzer_test.go
=> Remove cleanup of images stored in test registry

acceptance/analyzer_test.go, analyzer.go, analyzer_test.go, restorer.go, restorer_test.go, testdata/analyzer/cache_inconsistent_metadata.json
Fixes https://github.com/buildpacks/lifecycle/issues/589
=> Look in cache metadata to find cache layers if bp api >= 0.6

builder.go, buildpack/build.go
=> Add debug statements to builder

acceptance/restorer_test.go, acceptance/testdata/restorer/container/layers/analyzed.toml, acceptance/testdata/restorer/container/layers/group.toml, cmd/lifecycle/restorer.go
=> Restorer Acceptance Tests

.github/workflows/build.yml
Latest version fixes issue with `docker attach`
Signed-off-by: Micah Young <ymicah@vmware.com>
=> Removes pinned Docker CLI for Windows GHA

testhelpers/docker.go
Signed-off-by: Sonia Singla <soniasingla.1812@gmail.com>
=> Fix G204 by adding comment

go.mod, go.sum
=> Bump imgutil to enable checking read/write access for registry image

acceptance/analyzer_test.go, cmd/lifecycle/analyzer.go, cmd/lifecycle/creator.go, cmd/lifecycle/exporter.go
Please see associated spec PR: https://github.com/buildpacks/spec/pull/234
=> Updates for platform 0.7

acceptance/detector_test.go, acceptance/testdata/detector/container/cnb/custom_buildpacks/always_detect_buildpack/always_detect_buildpack_version/bin/detect, builder.go, buildpack/detect.go, buildpack/detect_test.go, buildpack/store.go, cmd/lifecycle/detector.go, detector.go, detector_test.go, env/build.go, env/build_test.go, testmock/buildpack.go
Resolves: https://github.com/buildpacks/lifecycle/issues/649
=> Show CNB_ASSETS env var conditionally during detect

acceptance/analyzer_test.go
=> Add acceptance test for analyzer dropping privileges

.github/workflows/build.yml, .github/workflows/draft-release.yml, .github/workflows/post-release.yml
=> Run pack acceptance tests on pushes to main & release/*

RELEASE.md
=> Add Documentation Requirements to Release Process

acceptance/detector_test.go, acceptance/testdata/detector/container/cnb/custom_buildpacks/always_detect_buildpack/always_detect_buildpack_version/buildpack.toml, buildpack/build.go, platform/v07/platform.go
=> Pause support for asset packages

Makefile
=> Remove docker compilation for linux binaries

.github/workflows/build.yml, .github/workflows/draft-release.yml, .github/workflows/post-release.yml, cosign.pub, tools/image/main.go
Resolves #671 
Tested on fork: https://github.com/natalieparellano/lifecycle/actions/runs/1061089355 and https://github.com/natalieparellano/lifecycle/actions/runs/1061110415
Note that this would require adding a `COSIGN_PASSWORD` and base64 encoded `COSIGN_PUBLIC_KEY` and `COSIGN_PRIVATE_KEY` as secrets to the lifecycle repo.
=> Cosign lifecycle images

acceptance/analyzer_test.go, acceptance/testdata/analyzer/analyze-image/container/cnb/platform-0.7-stack.toml, cmd/lifecycle/analyzer.go, cmd/lifecycle/creator.go, cmd/lifecycle/exporter.go, platform/files.go, platform/pre06/exit.go, platform/pre06/platform.go, platform/v06/exit.go, platform/v06/platform.go, platform/v07/exit.go, platform/v07/platform.go
=> Write run image in analyzed.toml and remove -run-image from exporter for platform 0.7+

DEVELOPMENT.md, tools/test-fork.sh
Tested on [fork](https://github.com/natalieparellano/lifecycle/actions/runs/1140708853), ha! 
=> Add script to make testing on forks easier

acceptance/analyzer_test.go, acceptance/exporter_test.go, acceptance/restorer_test.go, analyzer.go, analyzer_test.go, api/version.go, api/version_test.go, builder.go, buildpack/build.go, buildpack/detect.go, buildpack/v05/encoderdecoder.go, buildpack/v06/encoderdecoder.go, cmd/flags.go, cmd/launcher/main.go, cmd/lifecycle/analyzer.go, cmd/lifecycle/creator.go, cmd/lifecycle/exporter.go, cmd/lifecycle/restorer.go, env/env.go, exporter.go, exporter_test.go, launch/launcher.go, launch/process.go, launch/shell.go, layers.go, rebaser.go, restorer.go, restorer_test.go
This goes part of the way toward addressing #599
=> Introduce new api version helpers

cache_test.go, exporter.go, layers.go
@aemengo and I were debugging something yesterday and these statements were helpful.
=> Add debug statements for exporter

IMAGE.md, acceptance/analyzer_test.go, acceptance/exporter_test.go, acceptance/restorer_test.go, analyzer.go, analyzer_test.go, api/version.go, api/version_test.go, builder.go, buildpack/build.go, buildpack/detect.go, buildpack/v05/encoderdecoder.go, buildpack/v06/encoderdecoder.go, cmd/flags.go, cmd/launcher/main.go, cmd/lifecycle/analyzer.go, cmd/lifecycle/creator.go, cmd/lifecycle/exporter.go, cmd/lifecycle/restorer.go, env/env.go, exporter.go, exporter_test.go, launch/launcher.go, launch/process.go, launch/shell.go, layers.go, rebaser.go, restorer.go, restorer_test.go
This information should be copied to the Docker Hub repo "about" section.
=> Add information about buildpacksio/lifecycle

README.md
=> Update the README for platform 0.7

README.md, lifecycle.toml
This should be merged after #749
=> Update README with latest supported apis

analyzer_test.go, builder.go, cache_test.go, exporter_test.go, layers.go
Be consistent about the naming and use sbom instead of bom everywhere?
=> bom -> sbom 2

builder.go
=> Fix comment

cmd/lifecycle/creator.go
`podman` (alternative daemon docker dameon)  is closing connections after 20 seconds without any request. This is causing troubles when `build phase` takes longer than that and builder is trusted.
If builder is trusted then docker client's connection is established at the benign while process is still uid zero. Then the connection is supposed to be kept opened. However `podman` is closing it.
This commit sends `ping` request to the daemon each second while `build phase` is in progress.
**Steps to reproduce the issue**:
1. create simple Java app: `mvn archetype:generate -DarchetypeGroupId=org.apache.maven.archetypes -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeVersion=1.4 -DgroupId=com.example -DartifactId=test-bp -B`
2. in one terminal run `podman` as a service: `podman …
=> Keep connection opened by ping

priv/docker.go
Right now the connection is used in serial manner so it works just fine.
But if in we used parallel operation in future there would be broken IO,
and the error message doesn't say much.
```
===> EXPORTING
Reusing layers from image with id '946b1c1f946db00a91f90a485dc7e2200de3985dd06b503ed6286f5c54196839'
ERROR: failed to  image: verifying image "946b1c1f946db00a91f90a485dc7e2200de3985dd06b503ed6286f5c54196839": error during connect: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/946b1c1f946db00a91f90a485dc7e2200de3985dd06b503ed6286f5c54196839/json": net/http: HTTP/1.x transport connection broken: malformed HTTP status code "Red"
ERROR: failed to build: executing lifecycle: failed with status code: 1
```
=> Guard singleton connection

buildpack/build_test.go, buildpack/layers.go, cache/volume_cache.go, launch/exec_d_test.go, launch/testhelpers/syscall_unix.go
Clear up some issues the linter flags on `make test`.
=> Fix lint issues

acceptance/launcher_test.go, api/apis.go, buildpack/build.go, buildpack/build_test.go, launch/bash.go, launch/bash_test.go, launch/cmd.go, launch/cmd_test.go, launch/launch.go, launch/launcher.go, launch/launcher_test.go, launch/process.go, launch/process_internal_test.go, launch/shell.go, launch/testdata/profiles/pwd, launch/testdata/profiles/pwd.bat
Resolves #557
Thanks to @natalieparellano for review and feedback.
=> Process-specific working directory

analyzer.go, analyzer_test.go, cmd/lifecycle/analyzer.go, cmd/lifecycle/creator.go, cmd/lifecycle/restorer.go, internal/layer/sbom_restorer.go, internal/layer/sbom_restorer_test.go
See spec PR: https://github.com/buildpacks/spec/pull/278/files
=> Improve performance when restoring launch sboms from daemon

extender/kaniko/dockerfile_applier.go, test-extender.sh
Kaniko will now push cache layerse into the registry at `$REGISTRY_HOST/extended/buildimage/cache` and `$REGISTRY_HOST/extended/runimage/cache` - allowing for faster builds when the layer can be re-used.
=> Added default kaniko layer caching

DEVELOPMENT.md
They are required by the buildpack in buildpack/testdata/buildpack.
=> Add jq and yj as development prerequisites

buildpack/build_test.go, launch/launch.go
To reflect the request made here: https://github.com/buildpacks/spec/pull/290/files#r813238710
=> Change working-directory to working-dir

buildpack/bomfile.go, buildpack/build_test.go
=> Strip optional parameter before checking media type

README.md
=> Update README for latest apis

extender/extender.go
=> Extender should source env from extended build image before running builder

builder.go, cmd/lifecycle/builder.go, platform/files.go
=> Generate phase should update build plan to remove extension-provided deps

.github/workflows/build.yml
=> Upgrade GHA runner

builder.go, builder_test.go, buildpack/build_test.go, buildpack/files.go, exporter_test.go, launch/launch.go, launch/launch_test.go, launch/process.go, launch/process_test.go, platform/files.go
Thanks to the awesome work of @jabrown85 in https://github.com/buildpacks/lifecycle/pull/920 and https://github.com/buildpacks/lifecycle/pull/889, this PR is relatively small. I'll add comments to show user acceptance.
=> Implement overridable process args

.github/workflows/build.yml, README.md
Signed-off-by: Michael de Senna <desenna@gmail.com>
=> docs: fix coverage badge primarily

README.md, RELEASE.md, internal/selective/write_test.go
=> Update README with latest apis

cmd/lifecycle/rebaser.go, platform/lifecycle_inputs.go, platform/rebase_inputs.go
=> Fix: rebase does not require stack.toml

platform/lifecycle_inputs.go
These were added in #961 but are not actually used
=> Remove unused functions

.github/workflows/build.yml, .github/workflows/check-latest-release.yml, .github/workflows/post-release.yml, Makefile, acceptance/testdata/launcher/Dockerfile, acceptance/testdata/launcher/Dockerfile.windows, go.mod, platform/analyze_inputs.go, platform/build_inputs.go, platform/create_inputs.go, platform/detect_inputs.go, platform/export_inputs.go, platform/extend_inputs.go, platform/rebase_inputs.go, platform/restore_inputs.go
=> Updates go to version 1.19

.github/workflows/check-latest-release.yml
There is no go.mod before checkout
=> Fix check release workflow

DEVELOPMENT.md
to enshrine oral tradition from @naralleno
=> updating development mock generator instructions

.github/workflows/build.yml
Attempts to fix flakey image manifest creation
=> Ready release/0.16.1 (part 2)

acceptance/acceptance_test.go, acceptance/analyzer_test.go, acceptance/exporter_test.go, acceptance/phase_test.go, analyzer.go, analyzer_test.go, archive/extract.go, buildpack/bp_descriptor.go, buildpack/bp_descriptor_test.go, detector.go, detector_test.go, go.mod, go.sum, platform/files.go
for https://github.com/buildpacks/lifecycle/issues/742
=> Pull Os and Arch from RunImage; handle * Stacks

buildpack/bp_descriptor.go, buildpack/bp_descriptor_test.go
fix pack acceptance test break
=> put the breaks on single os detection by removing break

.grype.yaml
Signed-off-by: Joe Kimmel <jkimmel@vmware.com>
=> ignore non-impactful CVE

.grype.yaml
Signed-off-by: Joe Kimmel <jkimmel@vmware.com>
=> merge grype from release branch back into main

buildpack/bp_descriptor.go, buildpack/descriptor.go, buildpack/ext_descriptor.go, buildpack/ext_descriptor_test.go, buildpack/testdata/extension/by-id/D/v1/bin/detect.bat, buildpack/testdata/extension/by-id/D/v1/bin/generate.bat, buildpack/testdata/extension/by-id/D/v1/extension.toml, detector.go
see: https://github.com/buildpacks/lifecycle/issues/1057
=> extensions get the same targets validation as buildpacks

Makefile, acceptance/analyzer_test.go, acceptance/builder_test.go, acceptance/creator_test.go, acceptance/detector_test.go, acceptance/exporter_test.go, acceptance/extender_test.go, acceptance/restorer_test.go, archive/archive_test.go, archive/extract_test.go, archive/reader_test.go, archive/tar_windows_test.go, archive/writer_test.go, buildpack/bp_descriptor.go, cache/caching_image_test.go, cache/image_cache_test.go, cache/volume_cache_test.go, cache_test.go, cmd/lifecycle/analyzer.go, cmd/lifecycle/restorer.go, detector.go, detector_test.go, launch/cmd_test.go, launch/decode_test.go, launch/exec_d_test.go, launch/launcher_test.go, platform/files/analyzed.go, rebaser_test.go
Should fix the failure noted in https://github.com/buildpacks/pack/pull/1789#issuecomment-1581554411
=> Fixes from user testing

acceptance/testdata/extender/container/layers/generated/run/curl/Dockerfile, acceptance/testdata/extender/container/layers/generated/run/tree/Dockerfile, cmd/lifecycle/restorer.go, extender.go, extender_test.go, generator.go, platform/files/analyzed.go
Further fixes from user testing. This is the last PR hopefully!
=> Clarify log messages and omitempty

Makefile, acceptance/testdata/launcher/Dockerfile, acceptance/testdata/launcher/Dockerfile.windows, go.mod
Supersedes https://github.com/buildpacks/lifecycle/pull/1073
=> Bump go to 1.20

cache/image_deleter.go, cache/image_deleter_test.go
Fixing the PR https://github.com/buildpacks/lifecycle/pull/1136
=> Remove async go-subroutine delete keeping it sync

analyzer.go, builder.go, cache.go, cache_test.go, cmd/lifecycle/main.go, detector.go, exporter.go, extender.go, generator.go, log/logger.go, log/timelog.go, log/timelog_test.go, rebaser.go, restorer.go, save.go
cherry-pick of https://github.com/buildpacks/lifecycle/pull/1160
and cherry-pick of https://github.com/buildpacks/lifecycle/pull/1161
=> timestamp logs and phase error message cherry-picks

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/chore.md, .github/ISSUE_TEMPLATE/feature.md, .github/pull_request_template.md
Most notably:
* When creating a feature request, add a space for the RFC number
* Makes the template a bit more ergonomic by adding blank spaces
* Shortens some prompts
=> Adds a PR template and updates other templates

.github/workflows/check-latest-release.yml
The previous PR gave write permissions for the wrong scope. This time I actually checked it by running the workflow off of the branch and it worked as expected: https://github.com/buildpacks/lifecycle/actions/runs/6699287045/job/18203144888
=> Fix check release workflow (again)

.github/workflows/test-s390x.yml
Fix s390x workflow now that go is upgraded
---
Resolves #___
---
=> Fix s390x workflow now that go is upgraded

.github/workflows/build.yml, .github/workflows/draft-release.yml, .github/workflows/post-release.yml, Makefile
Adding support for the `ppc64le` architecture, to enhance the current multi-arch approach.
Support for `ppc64le` architecture was added
---
Resolves #1302
---
=> Adding build and packaging support for ppc64le arch

go.mod, go.sum
=> Bump imgutil to pick up fix from buildpacks/imgutil/pull/269

.github/workflows/test-s390x.yml
=> Try to fix test-s390x workflow

.github/workflows/test-s390x.yml
This PR fixes the issue related to IBM Cloud VSI creation during github actions for s390x architecture.
=> fix: ibmcloud CLI nic attachment issue for s390x testing

go.mod, go.sum
Fixes for [newer docker + containerd](https://github.com/buildpacks/pack/issues/2174), [podman](https://github.com/buildpacks/imgutil/pull/277)
---
Resolves #___
---
=> Bump imgutil to pick up fixes for containerd and podman

RELEASE.md
This is really mostly superficial, but I think it improves the readability of this doc. I reformatted and moved some sections for better visual hierarchy. I'm hoping this will help readers quickly find the information they need.
=> reformatted document

RELEASE.md
Adds more detail to release instructions
n/a
=> Add more detail to release instructions

.github/workflows/test-s390x.yml, Makefile, acceptance/testdata/launcher/Dockerfile, acceptance/testdata/launcher/Dockerfile.windows, cmd/lifecycle/restorer.go, go.mod, phase/rebaser.go
Upgrades go to 1.23
Upgrades go to 1.23
=> Upgrade go to 1.23

.grype.yaml
See https://github.com/buildpacks/lifecycle/pull/1414 for further context on why we need it
=> Silence non-impactful CVE

go.mod, go.sum
GHSA-29wx-vh33-7x7r-github.com/golang-jwt/jwt/v4
GHSA-w32m-9786-jp63-golang.org/x/net
Chore: Update golang-jwt/jwt/v4
Chore: Update golang.org/x/net
---
---
=> Updating go deps for grype

.github/workflows/draft-release.yml, acceptance/phase_test.go
=> Workflow Updates for 0.20.6

.github/workflows/draft-release.yml
debug draft step to see why it does not like recent release branch
=> debug draft step to see why it does not like recent release branch
